package id.ac.polinema.infohewan;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;

import java.util.ArrayList;
import java.util.List;

import id.ac.polinema.infohewan.adapter.GridAdapter;
import id.ac.polinema.infohewan.model.GambarHewan;

public class Daftar3Activity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_daftar3);
        RecyclerView teamsView = findViewById(R.id.rv_teams);

        List<GambarHewan> teams = new ArrayList<>();
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/3/3d/Charaxes_brutus_natalensis.jpg", "Kupu-kupu", "Kupu-kupu dan ngengat (rama-rama) merupakan serangga yang tergolong ke dalam ordo Lepidoptera, atau 'serangga bersayap sisik' (lepis, sisik dan pteron, sayap).\n" +
                "\n" +
                "Secara sederhana, kupu-kupu dibedakan dari ngengat alias kupu-kupu malam berdasarkan waktu aktifnya dan ciri-ciri fisiknya. Kupu-kupu umumnya aktif di waktu siang (diurnal), sedangkan ngengat kebanyakan aktif di waktu malam (nocturnal). Kupu-kupu beristirahat atau hinggap dengan menegakkan sayapnya, ngengat hinggap dengan membentangkan sayapnya. Kupu-kupu biasanya memiliki warna yang indah cemerlang, ngengat cenderung gelap, kusam atau kelabu. Meski demikian, perbedaan-perbedaan ini selalu ada perkecualiannya, sehingga secara ilmiah tidak dapat dijadikan pegangan yang pasti. (van Mastrigt dan Rosariyanto, 2005).\n" +
                "\n" +
                "Kupu-kupu dan ngengat amat banyak jenisnya, di Pulau Jawa dan Pulau Bali saja tercatat lebih dari 600 spesies kupu-kupu. Jenis ngengatnya sejauh ini belum pernah dibuatkan daftar lengkapnya, akan tetapi diduga ada ratusan jenis (Whitten dkk., 1999). Kupu-kupu pun menjadi salah satu dari sedikit jenis serangga yang tidak berbahaya bagi manusia."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/a/a6/Meat_eater_ant_feeding_on_honey02.jpg", "Semut", "Semut adalah semua serangga anggota suku Formicidae, bangsa Hymenoptera. Semut memiliki lebih dari 12.000 jenis (spesies), sebagian besar hidup di kawasan tropika. Sebagian besar semut dikenal sebagai serangga sosial, dengan koloni dan sarang-sarangnya yang teratur beranggotakan ribuan semut per koloni. Anggota koloni terbagi menjadi semut pekerja, semut pejantan, dan ratu semut. Dimungkinkan pula terdapat kelompok semut penjaga. Satu koloni dapat menguasai daerah yang luas untuk mendukung kehidupan mereka. Koloni semut kadang kala disebut \"superorganisme\" karena koloni-koloni mereka yang membentuk sebuah kesatuan.\n" +
                "\n" +
                "Meskipun ukuran tubuhnya yang relatif kecil, semut termasuk hewan terkuat di dunia. Semut jantan mampu menopang beban dengan berat lima puluh kali dari berat badannya sendiri, dapat dibandingkan dengan gajah yang hanya mampu menopang beban dengan berat dua kali dari berat badannya sendiri. Semut hanya tersaingi oleh kumbang badak yang mampu menopang beban dengan berat 850 kali berat badannya sendiri.\n" +
                "\n" +
                "Asam format disebut juga \"asam semut\" karena semut menghasilkan asam ini sebagai alat pertahanan diri."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/3/39/Plumpollen0060.jpg", "Lebah", "Lebah merupakan sekelompok besar serangga yang dikenal karena hidupnya berkelompok meskipun sebenarnya tidak semua lebah bersifat demikian. Semua lebah masuk dalam suku atau familia Apidae (ordo Hymenoptera: serangga bersayap selaput). Di dunia terdapat kira-kira 20.000 spesies lebah dan dapat ditemukan di setiap benua, kecuali Antartika.\n" +
                "\n" +
                "Sebagai serangga, ia mempunyai tiga pasang kaki dan dua pasang sayap. Lebah membuat sarangnya di atas bukit, di pohon kayu dan pada atap rumah. Sarangnya dibangun dari propolis (perekat dari getah pohon) dan malam yang diproduksi oleh kelenjar-kelelenjar lebah betina yang masih muda terdapat dalam badannya. Lebah memakan nektar bunga dan serbuk sari."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/4/48/Aedes_aegypti_biting_human.jpg", "Nyamuk", "Nyamuk adalah hewan yang termasuk dalam kelas serangga tergolong dalam order Diptera; genera termasuk Anopheles, Culex, Psorophora, Ochlerotatus, Aedes, Sabethes, Wyeomyia, Culiseta, dan Haemagoggus untuk jumlah keseluruhan sekitar 35 genera yang merangkum 2700 spesies. Nyamuk mempunyai dua sayap bersisik, tubuh yang langsing, dan enam kaki panjang; antarspesies berbeda-beda tetapi jarang sekali melebihi 15 mm.Dalam bahasa Inggris, nyamuk dikenal sebagai \"Mosquito\", berasal dari sebuah kata dalam bahasa Spanyol atau bahasa Portugis yang berarti lalat kecil. Penggunaan kata Mosquito bermula sejak tahun 1583. Di Britania Raya nyamuk dikenal sebagai gnats.\n" +
                "\n" +
                "Pada nyamuk betina, bagian mulutnya membentuk probosis panjang untuk menembus kulit mamalia (atau dalam sebagian kasus burung atau juga reptilia dan amfibi) untuk mengisap darah. Nyamuk betina memerlukan protein untuk pembentukan telur dan oleh karena diet nyamuk terdiri dari madu dan jus buah, yang tidak mengandung protein, kebanyakan nyamuk betina perlu mengisap darah untuk mendapatkan protein yang diperlukan. Nyamuk jantan berbeda dengan nyamuk betina, dengan bagian mulut yang tidak sesuai untuk mengisap darah. Agak rumit nyamuk betina dari satu genus, Toxorhynchites, tidak pernah mengisap darah. Larva nyamuk besar ini merupakan pemangsa jentik-jentik nyamuk yang lain."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/6/67/Flat_mite%2C_Brevipalpus_phoenicis.jpg", "Tungau", "Tungau adalah sekelompok hewan kecil bertungkai delapan yang, bersama-sama dengan caplak, menjadi anggota superordo Acarina. Tungau bukanlah kutu dalam pengertian ilmu hewan walaupun sama-sama berukuran kecil (sehingga beberapa orang menganggap keduanya sama). Apabila kutu sejati merupakan anggota Insecta (serangga), tungau lebih berdekatan dengan laba-laba dilihat dari kekerabatannya.\n" +
                "\n" +
                "Hewan ini merupakan salah satu avertebrata yang paling beraneka ragam dan sukses beradaptasi dengan berbagai keadaan lingkungan. Ukurannya kebanyakan sangat kecil sehingga kurang menarik perhatian hewan pemangsa besar dan mengakibatkan ia mudah menyebar.\n" +
                "\n" +
                "Banyak di antara anggotanya yang hidup bebas di air atau daratan, tetapi ada anggotanya yang menjadi parasit pada hewan lain (mamalia maupun serangga) atau tumbuhan, bahkan ada yang memakan kapang. Beberapa tungau diketahui menjadi penyebar penyakit (vektor) dan pemicu alergi. Walaupun demikian, ada pula tungau yang hidup menumpang pada hewan lain namun saling menguntungkan. Di bidang pertanian, tungau menimbulkan banyak kerusakan pada kualitas buah jeruk (umpamanya tungau karat buah Phyllocoptura oleivera Ashmed dan tungau merah Panonychus citri McGregor)[1], merusak daun ketela pohon dan juga daun beberapa tumbuhan Solanaceae (cabai dan tomat). Tungau juga menyebabkan penyakit skabies, penyakit pada kulit yang mudah menular.\n" +
                "\n" +
                "Ada lebih dari 45 ribu jenis tungau yang telah dipertelakan[2]. Para ilmuwan berpendapat, itu baru sekitar 5% dari kenyataan total jenis yang ada. Hewan ini dipercaya telah ada sejak sekitar 400 juta tahun. Ilmu yang mempelajari perikehidupan tungau dan caplak dikenal sebagai akarologi.\n" +
                "\n" +
                "Taksonomi tungau masih belum stabil karena banyaknya perubahan. Namun dapat dikatakan bahwa tungau mencakup semua anggota Acariformes, semua Parasitiformes kecuali Ixodida (caplak), dan beberapa familia dan genera yang belum pasti penempatannya."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/a/a2/Sarcophagid_fly_Portrait.jpg", "Lalat", "Lalat adalah jenis serangga dari ordo Diptera (berasal dari bahasa Yunani di berati dua dan ptera berarti sayap). Perbedaan yang paling jelas antara lalat dan ordo serangga lainnya adalah lalat memiliki sepasang sayap terbang dan sepasang halter, yang berasal dari sayap belakang, pada metatoraks (kecuali beberapa spesies lalat yang tidak dapat terbang). Satu-satunya ordo serangga lain yang memiliki dua sayap yang benar-benar berfungsi dan memiliki halter adalah Strepsiptera. Tetapi, berbeda dengan lalat, halter Strepsitera berada di mesotoraks dan sayap di metatoraks."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/2/2a/Gryllus_bimaculatus00.jpg", "Jangkrik", "Jangkrik[1], jengkerik atau cengkerik (Gryllidae) adalah serangga yang berkerabat dekat dengan belalang, memiliki tubuh kecil silindris, kepala hampir bulat dan sungut panjang seperti benang. Jangkrik adalah omnivora, dikenal dengan suaranya yang khas, yang dihasilkan oleh cengkerik jantan. Suara ini digunakan untuk menarik kedatangan betina dan mengusir kehadiran jantan lainnya. Suara cengkerik ini semakin keras dengan naiknya suhu sekitar. Di dunia dikenal sekitar 900 spesies cengkerik, termasuk di dalamnya adalah gangsir.\n" +
                "\n" +
                "Jangkrik telah dipelihara manusia sejak lama, dan di Asia dianggap sebagai pembawa keberuntungan. Laga cengkerik adalah sejenis permainan yang populer dan kerap kali melibatkan taruhan. Di Caraguatatuba, Brasil, cengkerik hitam di dalam ruangan dipercaya sebagai tanda datangnya penyakit, cengkerik hijau harapan, dan cengkerik kelabu uang. Dalam komedi, suara cengkerik biasanya digunakan untuk menandakan lawakan yang tidak lucu dan tidak membuat orang tertawa."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/9/9a/Mantis_devouring.jpg", "Mantis", "Belalang sentadu atau belalang sembah adalah serangga yang termasuk ke dalam ordo Mantodea. Dalam bahasa Inggris, serangga ini biasa disebut praying mantis karena sikapnya yang sering kali kelihatan seperti sedang berdoa. Kata mantis berasal dari bahasa Yunani \"Mantes\" yang berarti \"nabi\" atau \"peramal nasib\". Banyak sebutan dalam bahasa lokal, seperti congcorang (bahasa Sunda/bahasa Betawi), walang kadung/kèkèk (bahasa Jawa), dan mentadak (bahasa Melayu)."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/1/1e/Domino_cockroach_Therea_petiveriana.jpg", "Kecoa", "Kecoak, lipas, atau coro adalah serangga (kelas Insecta) dari ordo Blattodea yang kurang lebih terdiri dari 3.500 spesies dalam 6 famili. Kecoak terdapat hampir di seluruh belahan bumi, kecuali di wilayah kutub.\n" +
                "\n" +
                "Di antara spesies yang paling terkenal adalah kecoak amerika, Periplaneta americana, yang memiliki panjang 3 cm, kecoak jerman, Blattella germanica, dengan panjang ±1½ cm, dan kecoak asia, Blattella asahinai, juga dengan panjang sekitar 1½ cm. Kecoak sering dianggap sebagai hama dalam bangunan, walaupun hanya sedikit dari ribuan spesies kecoak yang termasuk dalam kategori ini."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/0/03/Sympetrum_flaveolum_-_side_%28aka%29.jpg", "Capung", "Capung atau sibar-sibar dan Capung Jarum adalah kelompok serangga yang tergolong ke dalam bangsa Odonata. Kedua macam serangga ini jarang berada jauh-jauh dari air, tempat mereka bertelur dan menghabiskan masa pra-dewasa anak-anaknya. Namanya dalam bahasa daerah adalah papatong (Sd.), kinjeng (Jw.), coblang (Jw.), kasasiur (bjn), tjapung\n" +
                "\n" +
                "Capung (subordo Anisoptera) relatif mudah dibedakan dari capung jarum (subordo Zygoptera). Capung umumnya bertubuh relatif besar dan hinggap dengan sayap terbuka atau terbentang ke samping. Sedangkan capung jarum umumnya bertubuh kecil (meskipun ada beberapa jenis yang agak besar), memiliki abdomen yang kurus ramping mirip jarum, dan hinggap dengan sayap-sayap tertutup, tegak menyatu di atas punggungnya."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/0/04/Young_grasshopper_on_grass_stalk02.jpg", "Belalang", "Belalang adalah serangga herbivora dari subordo Caelifera dalam ordo Orthoptera. Serangga ini memiliki antena yang hampir selalu lebih pendek dari tubuhnya dan juga memiliki ovipositor pendek. Suara yang ditimbulkan beberapa spesies belalang biasanya dihasilkan dengan menggosokkan femur belakangnya terhadap sayap depan atau abdomen (disebut stridulasi), atau karena kepakan sayapnya sewaktu terbang. Femur belakangnya umumnya panjang dan kuat yang cocok untuk melompat.\n" +
                "\n" +
                "Serangga ini umumnya bersayap, walaupun sayapnya kadang tidak dapat dipergunakan untuk terbang. Belalang betina umumnya berukuran lebih besar dari belalang jantan.\n" +
                "\n" +
                "Dalam Agama Islam, Belalang adalah salah satu dari dua hewan yang apabila telah terlebih dahulu mati masih dihalalkan untuk dimakan, bersama Ikan[1]"));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/9/93/Black_scorpion.jpg", "Kalajengking", "Kalajengking adalah sekelompok hewan beruas dengan delapan kaki (oktopoda) yang termasuk dalam ordo Scorpiones dalam kelas Arachnida. Kalajengking masih berkerabat dengan ketonggeng, laba-laba, tungau, dan caplak. Ada sekitar 2000 jenis kalajengking. Mereka banyak ditemukan selatan dari 49° U, kecuali Selandia Baru dan Antartika."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/6/69/Grapevinesnail_01.jpg", "Siput", "Siput adalah nama umum yang diberikan untuk anggota kelas moluska Gastropoda. Dalam arti sempit, istilah ini diberikan bagi mereka yang memiliki cangkang bergelung pada tahap dewasa. Dalam arti luas, yang juga menjadi makna \"Gastropoda\", mencakup siput dan siput telanjang (siput tanpa cangkang, dalam bahasa Jawa dikenal sebagai resrespo). Kelas Gastropoda menempati urutan kedua terbanyak dari segi jumlah spesies anggotanya setelah Insecta (serangga). Habitat, bentuk, tingkah laku, dan anatomi siput pun sangat bervariasi di antara anggota-anggotanya.\n" +
                "\n" +
                "Siput dapat ditemukan pada berbagai lingkungan yang berbeda: dari parit hingga gurun, bahkan hingga laut yang sangat dalam. Sebagian besar spesies siput adalah hewan laut. Banyak juga yang hidup di darat, air tawar, bahkan air payau. Kebanyakan siput merupakan herbivora, walaupun beberapa spesies yang hidup di darat dan laut dapat merupakan omnivora atau karnivora predator. Beberapa contoh Gastropoda adalah bekicot (Achatina fulica), siput kebun (Helix sp.), siput laut (Littorina sp.) dan siput air tawar (Limnaea sp.)"));
        teams.add(new GambarHewan("https://s.kaskus.id/images/2015/03/19/3727550_20150319010004.jpg", "Kissing Bug", "Kissing bug merupakan istilah yang diberikan kepada kumbang dengan nama latin Triatomine. Kumbang kecil dengan ukuran tak lebih dari beberapa inchi ini senang keluar di malam hari dan menggigit daerah bibir dan wajah manusia. Dari situlah istilah kissing bug muncul." +
                "\n" + "Layaknya nyamuk, kissing bug juga mengonsumsi darah mamalia sebagai makanannya. Sapi, kambing, kuda dan hewan ternak lainnya merupakan favorit kissing bug. Meski begitu, bukan tak mungkin serangga ini juga menggigit manusia.\n" +
                "\n" +
                "Gigitan ini bisa jadi penyakit karena mengandung bakteri Trypanosoma cruzi. Bakteri ini bisa menyebabkan penyakit Chagas dan membuat pasien mengalami demam, bahkan kematian.\n" +
                "\n" +
                "Meski begitu, Sarah mengatakan infeksi penyakit Chagas melalui kissing bug sangat jarang. Penelitian mengatakan dari 900 hingga 4.000 gigitan, hanya satu yang menyebabkan penyakit chagas.\n" +
                "\n" +
                "\"Serangganya harus menggigit Anda dengan dalam, dan memasukkan parasit ke dalam darah Anda. Kejadian ini sangat langka. Lebih langka daripada penularan penyakit melalui nyamuk,\" tutupnya."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/a/ab/Aptostichus_female.jpg", "Laba-laba", "Laba-laba adalah sejenis hewan berbuku-buku (arthropoda) dengan dua segmen tubuh, empat pasang kaki, tak bersayap, dan tak memiliki mulut pengunyah. Semua jenis laba-laba digolongkan ke dalam ordo Araneae; dan bersama dengan kalajengking, ketonggeng, tungau —semuanya berkaki delapan— dimasukkan ke dalam kelas Arachnida. Bidang studi mengenai laba-laba disebut arachnologi.\n" +
                "\n" +
                "Araneae adalah ordo terbesar dalam arachnida dan peringkat ketujuh dalam total keragaman spesies di antara seluruh ordo organismse.[2] Laba-laba dapat ditemukan di seluruh dunia di setiap benua kecuali di Antartika, dan telah bertahan lama di hampir semua habitat dengan perkecualian kolonisasi udara dan laut. Hingga Februari 2016, sedikitnya 45.800 spesies[3] dan 114 suku laba-laba telah dicatat oleh para taksonomis.[1] Tetapi, telah terjadi perpecahan di dalam komunitas ilmiah mengenai cara semua suku-suku tersebut diklasifikasikan karena sejak tahun 1900 telah ada lebih dari 20 klasifikasi berbeda telah diusulkan.[4]\n" +
                "\n" +
                "Laba-laba merupakan hewan pemangsa (karnivora), bahkan kadang-kadang kanibal. Mangsa utamanya adalah serangga. Hampir semua jenis laba-laba, dengan perkecualian sekitar 150 spesies dari suku Uloboridae dan Holarchaeidae, dan subordo Mesothelae, mampu menginjeksikan bisa melalui sepasang taringnya kepada musuh atau mangsanya. Meski demikian, dari puluhan ribu spesies yang ada, hanya sekitar 200 spesies yang gigitannya dapat membahayakan manusia.\n" +
                "\n" +
                "Tidak semua laba-laba membuat jaring untuk menangkap mangsa, akan tetapi semuanya mampu menghasilkan benang sutera—yakni helaian serat protein yang tipis namun kuat—dari kelenjar (disebut spinneret) yang terletak di bagian belakang tubuhnya. Serat sutera ini amat berguna untuk membantu pergerakan laba-laba, berayun dari satu tempat ke tempat lain, menjerat mangsa, membuat kantung telur, melindungi lubang sarang, dan lain-lain."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/9/9a/Mole_cricket02.jpg", "Mole Cricket", "Anjing tanah (Orong-orong) adalah serangga berukuran sedang, berwarna coklat terang hingga gelap, memiliki kulit pelindung yang tebal yang hidup di dalam tanah, dengan sepasang tungkai depan termodifikasi berbentuk cangkul untuk menggali tanah dan berenang. Orang Jawa menyebutnya orong-orong, di tanah Sunda disebut gaang, sementara dalam bahasa Toba disebut singke. Dalam bahasa Inggris dikenal sebagai mole cricket, atau \"jangkrik tikus mondok\". Semua anggotanya termasuk dalam keluarga Gryllotalpidae. Serangga yang kadang-kadang ditemukan berlari cepat di sudut pekarangan ini dapat pula terbang hingga sejauh 8 km dalam musim kawin. Hewan muda memiliki sayap yang pendek. Hewan ini aktif pada malam hari (nokturnal) dan pada musim dingin melakukan hibernasi. Pada musim kawin hewan ini dapat menghasilkan suara melalui mekanisme mirip jangkrik (dengan organ stridulasi), namun dengan suara yang jauh berbeda. Suaranya bersifat monoton, tanpa jeda, dan amat mengganggu pendengaran. Bila lubang persembunyiannya didekati, ia akan berhenti bersuara namun akan memulai lagi begitu merasa gangguan berlalu.\n" +
                "\n" +
                "Anjing tanah memakan segala, meskipun pada dasarnya ia adalah karnivora. Menunya adalah larva-larva serangga lain atau cacing. Bila kekurangan makanan ia akan memakan akar dan rumput-rumputan. Akibat tindakan yang terakhir ini anjing tanah kadang-kadang digolongkan sebagai hama tanaman. Pemangsanya bermacam-macam, mulai dari burung, ayam, tikus, sigung, hingga rubah.\n" +
                "\n" +
                "\n" +
                "Daur hidup anjing tanah.\n" +
                "Anjing tanah adalah hewan yang agak jarang terlihat karena lebih suka bersembunyi dalam lubang dan aktif pada malam hari mencari makan. Habitat yang disukai adalah ladang yang kering, pekarangan, serta lapangan rumput. Hewan ini dapat ditemukan di semua tempat, kecuali daerah dekat kutub bumi.\n" +
                "\n" +
                "Perannya dalam kehidupan manusia tidak terlalu penting. Hewan ini kadang-kadang digolongkan sebagai hama karena perilakunya merusak perakaran atau juga memakannya. Di Asia Timur hewan ini kadang-kadang digoreng dan disantap. Pemelihara burung juga menjadikan orong-orong sebagai bagian pakan hidup. Sekresi yang dihasilkan orong-orong di Cina menjadi bahan pengobatan, dan sekarang mulai diteliti khasiatnya secara farmasi.\n" +
                "\n" +
                "Anjing tanah di beberapa tempat berstatus terancam punah karena peralihan habitat dan erosi tanah. Pembasmian akibat dianggap hama juga mengganggu kehidupannya."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/d/d3/Coptotermes_formosanus_shiraki_USGov_k8204-7.jpg", "Rayap", "Rayap adalah serangga sosial anggota infraordo Isoptera, bagian dari ordo Blattodea[1][2] (kecoa) yang dikenal luas sebagai hama penting kehidupan manusia. Rayap bersarang di dan memakan kayu perabotan atau kerangka rumah sehingga menimbulkan banyak kerugian secara ekonomi. Rayap masih berkerabat dengan semut, yang juga serangga sosial. Dalam bahasa Inggris, rayap disebut juga \"semut putih\" (white ant) karena kemiripan perilakunya.\n" +
                "\n" +
                "\n" +
                "Kerusakan kayu akibat serangan rayap.\n" +
                "Sebutan rayap sebetulnya mengacu pada hewannya secara umum, padahal terdapat beberapa bentuk berbeda yang dikenal, sebagaimana pada koloni semut atau lebah sosial. Dalam koloni, rayap tidak memiliki sayap. Namun, beberapa rayap dapat mencapai bentuk bersayap yang akan keluar dari sarangnya secara berbondong-bondong pada awal musim penghujan (sehingga sering kali menjadi pertanda perubahan ke musim penghujan) di petang hari dan beterbangan mendekati cahaya. Bentuk ini dikenal sebagai laron atau anai-anai."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/f/f6/Chenille_chevrefeuille.jpg", "Ulat Bulu", "Ulat adalah tahap larva dari spesies dalam ordo Lepidoptera, yang mencakup kupu-kupu dan ngengat. Kebanyakan adalah pemakan tumbuhan walaupun beberapa spesies merupakan pemakan serangga. Kebanyakan ulat dianggap sebagai hama dalam pertanian. Banyak spesies ngengat dikenal karena tahap ulatnya menyebabkan kerusakan pada buah dan produk pertanian lainnya."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/a/a3/Nachtkerzenschwaermer_Raupe.jpg", "Larva", "Larva (Latin: larvae) adalah bentuk muda (juvenile) hewan yang perkembangannya melalui metamorfosis, seperti pada serangga dan amfibia. Bentuk larva dapat sangat berbeda dengan bentuk dewasanya, misalnya ulat dan kupu-kupu yang sangat berbeda bentuknya. Larva umumnya memiliki organ khusus yang tak terdapat pada bentuk dewasa dan juga tidak memiliki organ tertentu yang dimiliki pada bentuk dewasa. Suatu tahapan hidup disebut larva apabila dalam bentuk itu memiliki aktivitas yang tinggi (khususnya dalam bergerak dan mencari makanan).\n" +
                "\n" +
                "Kelompok hewan yang memiliki tahap larva cukup luas, mencakup serangga, berbagai Porifera, ubur-ubur dan kerabatnya (Coelenterata), berbagai Crustacea, Echinodermata, dan amfibia. Beberapa ikan yang baru menetas dari telurnya juga disebut sebagai larva. Tidak semua serangga memiliki bentuk yang disebut larva, karena hanya mereka yang menempuh jalur metamorfosis penuh (holometabola) yang memiliki bentuk larva. Serangga yang hanya menjalani metamorfosis tidak penuh (hemimetabola) bentuk mudanya disebut nimfa (nympha)."));

        GridAdapter adapter = new GridAdapter(this, teams);
        teamsView.setAdapter(adapter);

        RecyclerView.LayoutManager layoutManager = new GridLayoutManager(this, 2);
        teamsView.setLayoutManager(layoutManager);
    }
}
