package id.ac.polinema.infohewan;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;


import java.util.ArrayList;
import java.util.List;

import id.ac.polinema.infohewan.adapter.GridAdapter;
import id.ac.polinema.infohewan.model.GambarHewan;

public class DaftarActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_daftar);
        RecyclerView teamsView = findViewById(R.id.rv_teams);

        List<GambarHewan> teams = new ArrayList<>();
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/e/e1/Sumatran_Tiger_Berlin_Tierpark.jpg", "Harimau Sumatera", "Harimau sumatra (bahasa Latin: Panthera tigris sumatrae[2]) adalah subspesies harimau yang habitat aslinya di pulau Sumatra, dan merupakan satu dari enam subspesies harimau yang masih bertahan hidup hingga saat ini dan termasuk dalam klasifikasi satwa kritis yang terancam punah (critically endangered) dalam daftar merah spesies terancam yang dirilis Lembaga Konservasi Dunia IUCN. Populasi liar diperkirakan antara 400-500 ekor, terutama hidup di taman-taman nasional di Sumatra. Uji genetik mutakhir telah mengungkapkan tanda-tanda genetik yang unik, yang menandakan bahwa subspesies ini mungkin berkembang menjadi spesies terpisah, bila berhasil lestari.[3]\n" +
                "\n" +
                "Penghancuran habitat merupakan ancaman terbesar terhadap populasi saat ini. Pembalakan tetap berlangsung bahkan di taman nasional yang seharusnya dilindungi. Tercatat 66 ekor harimau sumatra terbunuh antara tahun 1998 dan 2000.\n" +
                "\n" +
                "Pada tahun 2017, Satuan Tugas Klasifikasi Kucing dari Cat Specialist Group merevisi taksonomi kucing sehingga populasi harimau yang hidup dan punah di Indonesia sekarang digolongkan sebagai P. t. sumatrae.[2]"));
        teams.add(new GambarHewan("https://fr.wikipedia.org/wiki/%C3%89l%C3%A9phant_de_Sumatra#/media/Fichier:Borobudur-Temple-Park_Elephant-cage-01.jpg", "Gajah", "Gajah adalah mamalia besar dari famili Elephantidae dan ordo Proboscidea. Secara tradisional, terdapat dua spesies yang diakui, yaitu gajah afrika (Loxodonta africana) dan gajah asia (Elephas maximus), walaupun beberapa bukti menunjukkan bahwa gajah semak afrika dan gajah hutan afrika merupakan spesies yang berbeda (L. africana dan L. cyclotis). Gajah tersebar di seluruh Afrika sub-Sahara, Asia Selatan, dan Asia Tenggara. Elephantidae adalah satu-satunya famili dari ordo Proboscidea yang masih ada; famili lain yang kini sudah punah termasuk mamut dan mastodon. Gajah afrika jantan merupakan hewan darat terbesar dengan tinggi hingga 4 m dan massa yang juga dapat mencapai 7.000 kg. Gajah memiliki ciri-ciri khusus, dan yang paling mencolok adalah belalai atau proboscis yang digunakan untuk banyak hal, terutama untuk bernapas, menghisap air, dan mengambil benda. Gigi serinya tumbuh menjadi taring yang dapat digunakan sebagai senjata dan alat untuk memindahkan benda atau menggali. Daun telinganya yang besar membantu mengatur suhu tubuh mereka. Gajah afrika memiliki telinga yang lebih besar dan punggung yang cekung, sementara telinga gajah asia lebih kecil dan punggungnya cembung.\n" +
                "\n" +
                "Gajah merupakan hewan herbivora yang dapat ditemui di berbagai habitat, seperti sabana, hutan, gurun, dan rawa-rawa. Mereka cenderung berada di dekat air. Gajah dianggap sebagai spesies kunci karena dampaknya terhadap lingkungan. Hewan-hewan lain cenderung menjaga jarak dari gajah, dan predator-predator seperti singa, harimau. hyena, dan anjing liar biasanya hanya menyerang gajah muda. Gajah betina cenderung hidup dalam kelompok keluarga, yang terdiri dari satu betina dengan anak-anaknya atau beberapa betina yang berkerabat beserta anak-anak mereka. Kelompok ini dipimpin oleh individu gajah yang disebut matriark, yang biasanya merupakan betina tertua. Gajah memiliki struktur kelompok fisi-fusi, yaitu ketika kelompok-kelompok keluarga bertemu untuk bersosialisasi. Gajah jantan meninggalkan kelompok keluarganya ketika telah mencapai masa pubertas, dan akan tinggal sendiri atau bersama jantan lainnya. Jantan dewasa biasanya berinteraksi dengan kelompok keluarga ketika sedang mencari pasangan dan memasuki tahap peningkatan testosteron dan agresi yang disebut musth, yang membantu mereka mencapai dominasi dan keberhasilan reproduktif. Anak gajah merupakan pusat perhatian kelompok keluarga dan bergantung pada induknya selama kurang lebih tiga tahun. Gajah dapat hidup selama 70 tahun di alam bebas. Mereka berkomunikasi melalui sentuhan, penglihatan, penciuman, dan suara; gajah juga menggunakan infrasonik dan komunikasi seismik untuk jarak jauh. Kecerdasan gajah telah dibandingkan dengan kecerdasan primata dan cetacea. Mereka tampaknya memiliki kesadaran diri dan menunjukkan empati kepada gajah lain yang hampir atau sudah mati.\n" +
                "\n" +
                "Gajah afrika digolongkan sebagai spesies yang rentan oleh International Union for Conservation of Nature (IUCN), sementara gajah asia diklasifikasikan sebagai spesies terancam. Salah satu ancaman terbesar bagi gajah adalah perdagangan gading yang memicu perburuan liar. Ancaman lain adalah kehancuran habitat dan konflik dengan penduduk setempat. Di sisi lain, gajah digunakan sebagai hewan pekerja di Asia. Dulu mereka pernah digunakan untuk perang; kini, gajah sering kali dipertontonkan di kebun binatang dan sirkus. Gajah dapat dengan mudah dikenali dan telah digambarkan dalam seni, cerita rakyat, agama, sastra, dan budaya populer."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/a/a9/Cheetah4.jpg", "Cheetah", "Citah (bahasa Sanskerta: chitraka, berarti \"berbintik\", bahasa Inggris: cheetah, bahasa Latin: Acinonyx jubatus) adalah anggota keluarga kucing (Felidae) yang berburu mangsa dengan menggunakan kecepatan dan bukan taktik mengendap-endap atau bergerombol. Hewan ini adalah hewan yang tercepat di antara hewan darat dan dapat mencapai kecepatan 110 km/jam dalam waktu singkat sampai 460 m, dengan akselerasi 0 – 100 km/jam dalam waktu 3,5 detik, lebih cepat dari beberapa mobil balap. Konon, selama bertahun-tahun citah hanya dikenal sebagai cerita hantu. Menurut cerita, binatang pemangsa besar dengan garis-garis mirip harimau pada tubuhnya ini sering membawa kabur orang-orang yang berada di perbatasan Mozambik. Penduduk di sana sering memberi julukan citah dengan \"magwa\".\n" +
                "\n" +
                "Citah juga dikenal sebagai pemangsa paling efisien di bumi. Mengejar dan menerkam mangsa hanya ketika mangsa itu ada dalam jangkauannya. Hewan ini tergolong pintar dengan kemampuannya mendeteksi hewan yang paling lemah. Ia menjatuhkan korban bukan dengan menerkam seperti singa atau harimau. Tapi pada sentuhan kecil di kaki belakang korban yang sedang berlari kencang. Saat korban jatuh, citah kemudian menerkam tengkuk korban untuk kemudian selanjutnya dicengkram hingga kehabisan darah.\n" +
                "\n" +
                "Meski terkenal sebagai pemburu menakutkan di padang Afrika, tetapi faktanya hanya 40% hingga 50% aktivitas berburunya yang membuahkan hasil. Pernah berkembang mitos bahwa kepanasan adalah penyebab mengapa citah gagal dalam berburu. Namun penelitian terbaru menunjukkan bahwa citah yang mulai memakan mangsanya sesaat setelah berhasil berburu mengalami kenaikan temperatur tubuh dua kali lipat dibandingkan dengan citah yang menghentikan aktivitas berburunya.[2]"));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/c/cf/Fawn_in_Forest_edit.jpg", "Rusa", "Rusa, sambar, atau menjangan (bahasa Inggris: deer) adalah hewan mamalia pemamah biak (ruminan) yang termasuk famili Cervidae. Salah satu ciri khas rusa adalah adanya antler (tanduk rusa), dan bukan tanduk, yang merupakan pertumbuhan tulang yang berkembang setiap tahun (biasanya pada musim panas) terutama pada rusa jantan (walaupun ada beberapa pengecualian). Ada sekitar 34 spesies rusa di seluruh dunia yang terbagi menjadi dua kelompok besar: kelompok rusa dunia lama yang termasuk subfamilia Muntiacinae dan Cervinae; serta kelompok rusa dunia baru, Hydropotinae dan Odocoilinae."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/7/74/Crocodile_Crocodylus-porosus_amk.jpg", "Buaya", "Buaya adalah reptil bertubuh besar yang hidup di air. Secara ilmiah, buaya meliputi seluruh spesies anggota suku Crocodylidae, termasuk pula buaya sepit (Tomistoma schlegelii). Meski demikian nama ini dapat pula dikenakan secara longgar untuk menyebut ‘buaya’ aligator, kaiman dan gavial; yakni kerabat-kerabat buaya yang berlainan suku.\n" +
                "\n" +
                "Buaya umumnya menghuni habitat perairan tawar seperti sungai, danau, rawa dan lahan basah lainnya, namun ada pula yang hidup di air payau seperti buaya muara. Makanan utama buaya adalah hewan-hewan bertulang belakang seperti bangsa ikan, reptil dan mamalia, kadang-kadang juga memangsa moluska dan krustasea bergantung pada spesiesnya. Buaya merupakan hewan purba, yang hanya sedikit berubah karena evolusi semenjak zaman dinosaurus.\n" +
                "\n" +
                "Dikenal pula beberapa nama daerah untuk menyebut buaya, seperti misalnya buhaya (Sd.); buhaya (bjn); baya atau bajul (Jw.); bicokok (Btw.), bekatak, atau buaya katak untuk menyebut buaya bertubuh kecil gemuk; senyulong, buaya jolong-jolong (Mly.), atau buaya julung-julung untuk menyebut buaya ikan; buaya pandan, yakni buaya yang berwarna kehijauan; buaya tembaga, buaya yang berwarna kuning kecoklatan; dan lain-lain.\n" +
                "\n" +
                "Dalam bahasa Inggris buaya dikenal sebagai crocodile. Nama ini berasal dari penyebutan orang Yunani terhadap buaya yang mereka saksikan di Sungai Nil, krokodilos; kata bentukan yang berakar dari kata kroko, yang berarti ‘batu kerikil’, dan deilos yang berarti ‘cacing’ atau ‘orang’. Mereka menyebutnya ‘cacing bebatuan’ karena mengamati kebiasaan buaya berjemur di tepian sungai yang berbatu-batu."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/7/73/Lion_waiting_in_Namibia.jpg", "Singa", "Singa (bahasa Sanskerta: Siṃha, atau dalam bahasa Latin: Panthera leo) adalah spesies hewan dari keluarga felidae atau jenis kucing. Singa merupakan hewan yang hidup berkelompok. Biasanya terdiri dari seekor jantan dan banyak betina. Kelompok ini menjaga daerah kekuasaannya. Umur singa antara 10 sampai 15 tahun di alam bebas, tetapi dalm penangkaran memungkinkan lebih dari 20 tahun.\n" +
                "\n" +
                "Singa betina jauh lebih aktif dalam berburu, sedangkan singa jantan lebih santai bersikap menunggu dan meminta jatah dari hasil buruan para betinanya. Singa jantan dipercaya lebih unggul dan perkasa dibandingkan dengan kucing besar lainnya, tetapi kelemahan singa ialah tidak bisa memanjat pohon sebagus kucing-kucing besar lainnya. Singa jantan ditumbuhi bulu tebal di sekitar tengkuknya, hal ini lebih menguntungkan untuk melindungi tengkuknya, terutama dalam perkelahian bebas antara kucing besar yang cenderung menerkam tengkuk untuk melumpuhkan musuhnya.\n" +
                "\n" +
                "Kucing besar lainnya, seperti citah dan macan tutul memiliki ukuran tubuh jauh lebih kecil dibanding singa. Walaupun berasal dari keluarga yang sama dengan harimau, singa tidak suka dengan air. Berbeda dengan harimau yang suka dengan air.\n" +
                "\n" +
                "Singa yang terkenal di dunia adalah Bongo. Singa yang menjadi bintang film dalam film George of the Jungle. Bongo adalah singa paling jinak yang meninggal karena sakit paru-paru. Singa kedua yang paling jinak di dunia adalah Zamba yang merupakan peliharaan Ralph Helfer."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/9/94/Monkey_batu.jpg", "Monyet", "Monyet adalah istilah untuk semua anggota primata yang bukan prosimia (\"pra-kera\", seperti lemur dan tarsius) atau kera, baik yang tinggal di Dunia Lama maupun Dunia Baru. Hingga saat ini dikenal 264 jenis monyet yang hidup di dunia. Tidak seperti kera, monyet biasanya berekor dan berukuran lebih kecil. Monyet diketahui dapat belajar dan menggunakan alat untuk membantunya dalam mendapatkan makanan.\n" +
                "\n" +
                "Pengelompokan monyet bersifat parafiletik, karena monyet Dunia Lama (Cercopithecoidea) sebenarnya lebih dekat kekerabatan genetiknya dengan kera (Hominidae), daripada monyet Dunia Baru (Platyrrhini).\n" +
                "\n" +
                "Monyet terbesar adalah mandrill. Beberapa monyet dalam bahasa sehari-hari juga sering disebut sebagai kera.\n" +
                "\n" +
                "Beberapa monyet telah dimanfaatkan manusia sebagai hewan timangan atau hewan untuk membantu pekerjaan sehari-hari. Monyet ekor panjang (Macaca fascicularis) adalah hewan yang paling biasa berinteraksi dengan manusia dan sering dipelihara sebagai hewan timangan, hewan sirkus, atau percobaan laboratorium. Ia juga primata pertama yang pernah ke angkasa luar. Beruk dipelihara di beberapa tempat di Sumatra dan Malaya untuk dilatih sebagai pemetik kelapa.\n" +
                "\n" +
                "Monyet di hutan gunung Bunder menggerakkan pepohonan di siang hari, berlompatan dari satu dahan ke dahan yang lain dan diam bila ada pendaki gunung yang lewat. Mungkin di situ monyet hidup berdampingan dengan macan akar dan ular. Di Sumatra Barat, tepatnya Danau Maninjau, penginapan bersebelahan dibangunnya dengan hutan dan monyet dapat dengan mudah menanjakn pohondan memasuki teras hotel dekat kolam renang. Di perjalanan naik turun ke arah danau Maninjai, monyet monyet leluasa berkeliaran dan seperti menunggu makanan yang dilepmar oleh pelancong."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/3/34/White_Bengal_tiger_Miami_MetroZoo.jpg", "Harimau Putih", "Harimau putih adalah harimau yang membawa gen resesif yang menghasilkan pewarnaan pucatnya. Ada juga satu fitur genetik yang menyebabkan belangnya juga berwarna pudar. Ini terjadi bila seekor harimau mewarisi dua salinan gen resesif untuk pewarnaan pudar yang jarang terjadi. Harimau putih berhidung merah jambu, berpusat kaki merah jambu, berkulit kelam kelabu, bermata biru es, dan berbulu putih atau putih kuning berbelang hitam, kelabu atau coklat.[1]" +
                "\n" + "Harimau putih bukan albino atau subspesies yang berbeda, jadi bisa berkembangbiak bersama harimau biasa yang berwarna jingga, anaknya adalah heterozigot karena gen pemutihan yang resesif, maka bulunya berwarna jingga, melainkan induk yang jingga pun heterozigot, maka anaknya ada 50% peluang menjadi putih resesif ganda atau jingga heterozigot. Jika dua harimau heterozigot berbiak pula, maka rata-rata 25% anaknya akan berwarna putih, 50% jingga heterozigot (pembawa gen putih) dan 25% yang tersisa jingga homozigot tanpa gen putih. Pada 1970-an, sepasang harimau jingga heterozigot bernama Sashi dan Ravi melahirkan 13 anak dalam Zoo Alipore, tiga darinya berwarna putih. Jika dua harimau putih berbiak, hasilnya 100% anaknya berupa harimau putih homozigot. Harimau yang homozigot untuk gen putihnya dapat juga menjadi heterozigot atau homozigot untuk gen yang lain. Persoalan apakah seseekor harimau itu heterozigot atau homozigot tergantung pada konteks gen yang mana sedang dibahas. Pembiakbakaan dalam mendorong kehomozigotan, maka dijadikan strategi melahirkan harimau putih.\n" +
                "\n" +
                "Dibandingkan dengan harimau jingga tanpa gen putih, harimau putih biasanya lebih besar dari lahir lagi hingga mencapai ukuran dewasa sepenuhnya. Inilah salah satu kelebihan yang dimiliki oleh harimau putih dalam habitat liar meskipun berwarna tersebut. Harimau jingga heterozigot pula juga lebih besar dibandingkan harimau jingga yang lain. Kailash Sankhala, direktur kebun binatang New Delhi pada 1960-an mengatakan, \"Salah satu fungsi gen putih ini berkemungkinan untuk mempertahankan suatu 'gen ukuran' dalam populasi harimau dengan ukuran yang lebih besar dari biasanya.\"\n" +
                "\n" +
                "Harimau putih individu yang berbelang gelap tercatat sebagai subspesies harimau benggala dan harimau siberia (Panthera tigris altaica) dalam penangkaran, mungkin juga tergolong ke dalam subspesies lainnya. Kini ada ratusan harimau putih dalam penangkaran di seluruh dunia, sekitar seratus dari India dan jumlahnya semakin bertambah. Populasi harimau putih modern mencakup subspesies harimau benggala sejati dan campuran harimau benggala dan harimau siberia tetapi tidak dipastikan apakah gen resesif pemutih ini berasal dari harimau benggala saja atau semua nenek moyangnya berasal dari harimau siberia."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/6/6d/Ceratotherium_simum_kwh_2.jpg", "Badak", "Badak (bahasa Inggris: rhinoceros) adalah lima spesies hewan dari famili Rhinocerotidae, ordo Perissodactyla yang kesemuanya berasal dari Afrika atau Asia." +
                "\n" + "Badak memiliki karakteristik:\n" +
                "\n" +
                "Herbivora berukuran besar yang dapat mencapai bobot lebih dari satu ton.\n" +
                "Satu atau dua cula pada bagian tengah dahi. Jika berjumlah dua, salah satu terletak di depan yang lainnya (tidak bersisian).\n" +
                "Kulit dengan tebal berkisar 1.5 – 5 cm yang terbentuk dari lapisan kolagen.\n" +
                "Memiliki indra pendengaran dan penciuman yang tajam, tetapi tidak dapat melihat jauh.\n" +
                "Sebagian besar badak dapat hidup melebihi 40 tahun.\n" +
                "Walaupun termasuk herbivora, badak adalah hewan yang berbahaya. Di India dan Nepal, badak merupakan penyebab utama kematian manusia, melebihi yang jumlah yang disebabkan oleh harimau dan macan tutul. Badak bahkan diketahui pernah menyerang gajah pembawa wisatawan."));
        teams.add(new GambarHewan("https://images5.alphacoders.com/958/958580.jpg", "Naga", "Naga adalah sebutan umum untuk makhluk mitologi yang berwujud reptil berukuran raksasa. Makhluk ini muncul dalam berbagai kebudayaan. Pada umumnya berwujud seekor ular besar, tetapi ada pula yang menggambarkannya sebagai kadal bersayap yang memilik beberapa kepala dan dapat menghembuskan nafas api. Naga dipercaya dapat ditaklukan lewat musik." +
                "\n" + "Naga, dalam berbagai peradaban dikenal dengan nama dragon (Inggris), draken (Skandinavia), Liong (Tiongkok), dikenal sebagai makhluk superior yang berwujud menyerupai ular, kadang bisa menyemburkan api, habitatnya di seluruh ruang (air, darat, udara). Meskipun penggambaran wujudnya berbeda-beda, tetapi secara umum spesifikasi makhluk tersebut digambarkan sebagai makhluk sakti.\n" +
                "\n" +
                "Sosok naga di dunia barat digambarkan sebagai monster, cenderung merusak dan bersekutu dengan kekuatan gelap. Dicitrakan sebagai tokoh antagonis yang seharusnya dihancurkan. Seseorang bisa mendapat gelar pahlawan atau ksatria dengan membunuh naga. Pendek kata, naga adalah ancaman bagi manusia.\n" +
                "\n" +
                "Tidak demikian halnya dengan citra naga di peradaban timur. Di Tiongkok, naga dianggap sebagai sosok yang bijaksana dan agung layaknya dewa. Naga adalah satu-satunya hewan mitos yang menjadi simbol Shio. Budaya Minangkabau mengenal dongeng Ngarai Sianok yang diciptakan oleh Sang Naga. Hiasan berbentuk naga juga sangat lekat dengan budaya Jawa, umumnya terdapat di gamelan, pintu candi dan gapura, sebagai lambang penjaga. Masyarakat Dayak juga menggambarkan Naga sebagai penguasa dunia bawah, dan Burung Enggang sebagai penguasa dunia atas. Naga di peradaban timur mendapat tempat terhormat, karena meskipun mempunyai kekuatan dahsyat yang bisa menghancurkan, tetapi tidak semena-mena dan bahkan bisa mengayomi.\n" +
                "\n" +
                "Naga atau Ular menurut pandangan kebanyakan Orang Indonesia, dianggap sebagai lambang dunia bawah. Sebelum Zaman Hindu (Neolithicum), di Indonesia terdapat anggapan bahwa dunia ini terbagi menjadi dua bagian, yaitu dunia bawah dan dunia atas, dan masing-masing mempunyai sifat yang bertentangan. Dunia bawah antara lain dilambangkan dengan bumi, bulan, gelap, air, ular, kura-kura, buaya. Sedangkan dunia atas dilambangkan dengan matahari, terang, atas, kuda, rajawali.[1]\n" +
                "\n" +
                "Pandangan semacam itu juga hampir merata di seluruh bangsa Asia. Dalam cerita Mahabarata maupun pandangan kebanyakan Orang Indonesia sendiri sebelum Zaman Hindu, naga atau ular selalu berhubungan dengan air, sedangkan air mutlak diperlukan sebagai sarana pertanian."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/8/8c/PorcupineCabelasSpringfield0511.jpg", "Landak", "Landak adalah hewan pengerat (Rodentia) yang memiliki rambut yang tebal dan berbentuk duri tajam. Hewan ini ditemukan di Asia, Afrika, maupun Amerika, dan cenderung menyebar di kawasan tropika. Landak merupakan hewan pengerat terbesar ketiga dari segi ukuran tubuh, setelah kapibara dan berang-berang. Hewan ini agak \"membulat\" serta tidak terlalu lincah apabila dibandingkan dengan tikus. Karena rambut durinya, hewan lain yang mirip namun bukan pengerat, seperti hedgehog dan landak semut (Echidna), juga dikenali sebagai \"landak\".\n" +
                "\n" +
                "Landak secara umum adalah herbivora, dan menyukai daun, batang, khususnya bagian kulit kayu. Karena hal inilah banyak landak dianggap sebagai hama tanaman pertanian. Meskipun demikian, orang juga menjadikan landak sebagai salah satu bahan pangan[1]. Sate landak merupakan salah satu menu khas dari Kabupaten Karanganyar.\n" +
                "\n" +
                "Landak yang biasa dikenal orang adalah Hystrix, tetapi secara umum landak juga dipakai untuk menyebut anggota dari suku/famili Erethizontidae (landak Dunia Baru, marga: Coendou, Sphiggurus, Erethizon, Echinoprocta, dan Chaetomys) dan Hystricidae (landak Dunia Lama, marga: Atherurus, Hystrix, dan Trichys)."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/4/43/Charging_Leopard-001.JPG", "Leopard", "Macan tutul (bahasa Latin: Panthera pardus) adalah salah satu dari empat kucing besar. Hewan ini dikenal juga dengan sebutan harimau dahan karena kemampuannya memanjat. Pada mulanya, orang berpikiran bahwa macan tutul adalah hibrida dari singa dan harimau, sehingga muncul nama \"leopard\" di kalangan peneliti Eropa awal. Macan tutul jawa (P. p. melas) adalah fauna identitas Jawa Barat dan termasuk hewan yang terancam punah di Indonesia.\n" +
                "\n" +
                "Macan tutul berukuran besar, dengan panjang tubuh antara satu sampai dua meter. Spesies ini pada umumnya memiliki bulu berwarna kuning kecoklatan dengan bintik-bintik berwarna hitam. Bintik hitam dikepalanya berukuran lebih kecil. Macan tutul betina serupa, dan berukuran lebih kecil dari jantan.\n" +
                "\n" +
                "Daerah sebaran macan tutul adalah di benua Asia dan Afrika. Spesies ini sempat dianggap memiliki banyak anakjenis (lebih dari 30 subspesies) yang ditemukan di segala macam habitat, mulai dari hutan tropis, gurun, savanah, pegunungan dan daerah pemukiman, tetapi sekarang direduksi menjadi hanya sembilan setelah dilakukan pengujian molekuler.\n" +
                "\n" +
                "Macan Tutul adalah hewan penyendiri, yang saling menghindari satu sama lain. Spesies ini lebih aktif di malam hari. Karena tingkat kematian anak yang tinggi, betina biasanya mempunyai satu sampai dua anak, yang tinggal bersama induknya sampai macan muda berumur sekitar antara satu setengah sampai dua tahun.\n" +
                "\n" +
                "Macan Tutul merupakan pemburu oportunitis, yang menggunakan segala kesempatan untuk mendapatkan mangsanya. Mereka memakan hampir segala mangsa dari berbagai ukuran. Mangsa utamanya terdiri dari aneka hewan menyusui, binatang pengerat, ikan, burung, monyet dan binatang-binatang lain yang terdapat disekitar habitatnya.\n" +
                "\n" +
                "Pada umumnya, Macan Tutul menghindari manusia. Namun macan yang kurang sehat, kelaparan atau terluka sehingga tidak dapat berburu mangsa yang biasa, dapat memangsa manusia. Ada peristiwa mengenai seekor Macan Tutul jantan di Rudraprayag memangsa lebih dari 125 jiwa, dan seekor Macan Tutul betina yang disebut \"Macan Tutul Panar\" memangsa lebih dari 400 jiwa pada awal abad ke-20 di India.\n" +
                "\n" +
                "Beberapa subspesies dari Macan Tutul seperti Macan Kumbang dari Indonesia terancam punah, tetapi secara umum Macan Tutul dievaluasikan sebagai Beresiko Rendah di dalam IUCN Red List."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/0/03/Vulpes_vulpes_laying_in_snow.jpg", "Rubah", "Rubah adalah karnivora kecil. Terdapat 27 spesies rubah, mereka adalah hewan omnivora dan anggota terkecil famili Canidae (mamalia yang berhubungan dengan anjing). Mereka adalah pelari cepat dan tangkas.\n" +
                "\n" +
                "Rubah dapat ditemui di semua benua, hidup di hutan, semak-semak dan padang pasir. Kebanyakan rubah makan tikus, vole, kelinci, telur burung, serangga besar dan daging bangkai. Di Britania Raya, terdapat olahraga umum untuk berburu rubah dengan kuda dan anjing."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/9/9e/Giraffe_Mikumi_National_Park.jpg", "Jerapah", "Jerapah atau zarafah (nama ilmiah: Giraffa camelopardalis) adalah mamalia berkuku genap endemik Afrika dan merupakan spesies hewan tertinggi yang hidup di darat. Jerapah jantan dapat mencapai tinggi 4,8 sampai 5,5 meter dan memiliki berat yang dapat mencapai 1.360 kilogram. Jerapah betina biasanya sedikit lebih pendek dan lebih ringan.\n" +
                "\n" +
                "Jerapah berkerabat dengan rusa dan sapi tetapi dari suku yang berbeda, yaitu Giraffidae yang mencakup jerapah sendiri dan kerabat terdekatnya, okapi. Habitat aslinya mencakup area dari Chad sampai dengan Afrika Selatan\n" +
                "\n" +
                "Nama spesiesnya camelopardalis diambil dari nama dalam latin, karena dianggap sebagai bastar unta (camel) dan macan tutul (leopard). Nama camelopardalis dipakai oleh Plinius senior dalam ensiklopedia yang ditulisnya. Nama ini juga dipakai sebagai nama salah satu rasi bintang. Nama \"jerapah\" sendiri dipinjam dari nama hewan ini dalam bahasa Arab (الزرافة, zirafah)."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/b/be/Banteng_Jawa_%28Bos_javanicus%29.jpg", "Banteng", "Banteng atau tembadau (dari bahasa Jawa, banṭhèng), Bos javanicus, adalah hewan yang sekerabat dengan sapi dan ditemukan di Myanmar, Thailand, Kamboja, Laos, Vietnam, Kalimantan, Jawa, dan Bali. Banteng dibawa ke Australia Utara pada masa kolonisasi Britania Raya pada tahun 1849 dan sampai sekarang masih lestari.\n" +
                "\n" +
                "Terdapat tiga anak jenis banteng liar: B. javanicus javanicus (di Jawa, Madura, dan Bali), B. javanicus lowi (di Kalimantan, jantannya berwarna coklat bukan hitam), dan B. javanicus birmanicus (di Indocina). Anak jenis yang terakhir digolongkan sebagai Terancam oleh IUCN.\n" +
                "\n" +
                "Banteng dapat mencapai tinggi sekitar 1,6m di bagian pundaknya dan panjang badan 2,3 m. Berat banteng jantan biasanya sekitar 680 – 810 kg — jantan yang sangat besar bisa mencapai berat satu ton — sedangkan betinanya lebih ringan. Banteng memiliki bagian putih pada kaki bagian bawah dan pantat, punuk putih, serta warna putih di sekitar mata dan moncongnya, walaupun terdapat sedikit dimorfisme seksual pada ciri-ciri tersebut. Banteng jantan memiliki kulit berwarna biru-hitam atau atau coklat gelap, tanduk panjang melengkung ke atas, dan punuk di bagian pundak. Sementara, betinanya memiliki kulit coklat kemerahan, tanduk pendek yang mengarah ke dalam dan tidak berpunuk.\n" +
                "\n" +
                "Banteng memakan rumput, bambu, buah-buahan, dedaunan, dan ranting muda. Banteng umumnya aktif baik malam maupun siang hari, tetapi pada daerah permukiman manusia, mereka beradaptasi sebagai hewan nokturnal. Banteng memiliki kecenderungan untuk berkelompok pada kawanan berjumlah dua sampai tiga puluh ekor. Di Jawa, Taman Nasional Ujung Kulon, Taman Nasional Meru Betiri, Taman Nasional Bali Barat, Taman Nasional Alas Purwo dan Taman Nasional Baluran menjadi pertahanan terakhir hewan asli Asia Tenggara ini."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/a/aa/Nijlpaard.jpg", "Kuda Nil", "Kuda nil (bahasa Latin: Hippopotamus amphibius) atau hippo (bahasa Yunani: ἱπποπόταμος, hippopotamos, dari ἵππος, hippos, \"kuda\", dan ποταμός, potamos, \"sungai\") adalah mamalia dari keluarga Hippopotamidae yang berukuran besar, omnivora, dan berasal dari Afrika sub-Sahara. Kuda nil adalah hewan darat terbesar ketiga setelah gajah dan badak putih." +
                "\n" + "Kuda nil memiliki tubuh yang besar dan berat, serta kulit kelabu gelap. Mereka juga memiliki gading besar yang biasa mereka gunakan untuk mempertahankan diri dari predator. Kuda nil memiriki ciri khas tubuh yang besar, mulut dan gigi yang sangat besar, empat kaki yang pendek dan gemuk, serta badan yang hampir tidak berambut. Kuda nil dewasa memiliki berat 1.5 sampai 3 ton. Meskipun bertubuh besar dan berkaki pendek, kuda nil mampu berlari dengan cepat. Untuk jarak pendek, mereka mampu berlari secepat 30 km/jam, lebih cepat dari kecepatan lari manusia pada umumnya. Kuda nil memiliki watak agresif dan dianggap salah satu hewan paling berbahaya di Afrika.\n" +
                "\n" +
                "Kerabat kuda nil yang paling dekat adalah kelompok Cetacea, seperti paus, lumba-lumba dan pesut. Selain itu kuda nil juga berkerabat dengan babi dan hewan-hewan berkuku genap lainnya."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/1/1f/Mammuthus_primigenius_St_Petersbu_2.JPG", "Mammoth", "Mamut adalah genus gajah purba yang telah punah. Ukuran tubuhnya lebih besar daripada gajah normal yang ada di dunia saat ini. Gadingnya melingkar membentuk kurva ke arah dalam dan, dalam spesies utara, dengan rambut panjang. Mereka hidup dalam masa Pleistosen sejak 1,6 juta tahun lalu sampai sekitar 10.000 tahun lalu. Kata mamut berasal dari bahasa Rusia (мамонт).\n" +
                "\n" +
                "Ada kesalahpahaman bahwa mamut lebih besar dari gajah. Spesies terbesar mamut yang diketahui, Mammoth Sungai Songhua, memiliki tinggi sekurangnya 5 meter pada pundaknya. Mamut umumnya memiliki berat 6-8 ton, tetapi mamut jantan yang besar beratnya dapat mencapai 12 ton. Gading mamut sepanjang 3,3 meter ditemukan di utara Lincoln, Illinois tahun 2005. Sebagian besar spesies mamut memiliki ukuran sebesar Gajah Asia modern."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/e/e0/Cougar_25.jpg", "Puma", "Puma atau Cougar atau Singa gunung adalah binatang mamalia yang tergolong dalam kelompok kucing besar. Puma umumnya dijumpai di kawasan benua Amerika. Puma mempunyai genetik yang lebih dekat dengan kucing dibandingkan dengan singa." +
                "\n" + "Makanan cougar umumnya adalah rusa, tupai, ikan, dan lain-lain.\n" +
                "\n" +
                "Cougar menyerang mangsanya dengan menyergap atau menyerang tiba-tiba karena ia memiliki stamina yang tidak terlalu bagus. Hal tersebut menyebabkan cougar harus menghemat energi, seperti singa dan kucing."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/b/be/Orang_Utan%2C_Semenggok_Forest_Reserve%2C_Sarawak%2C_Borneo%2C_Malaysia.JPG", "Orang Utan", "Orang utan (atau orangutan, nama lainnya adalah mawas) adalah salah satu jenis kera besar dengan lengan panjang dan berbulu kemerahan atau cokelat, yang hidup di hutan tropis Indonesia dan Malaysia, khususnya di Pulau Kalimantan dan Sumatra.[1][2]" +
                "\n" + "Istilah \"orang utan\" diambil dari kata dalam bahasa melayu, yaitu 'orang' yang berarti manusia dan 'utan' yang berarti hutan. Orang utan mencakup dua sub-spesies, yaitu orang utan sumatera (Pongo abelii) dan orang utan kalimantan (borneo) (Pongo pygmaeus).[3] Orang utan memiliki hubungan kekerabatan yang dekat dengan manusia dengan tingkat kesamaan DNA sebesar 96,4%.[4]"));

        GridAdapter adapter = new GridAdapter(this, teams);
        teamsView.setAdapter(adapter);

        RecyclerView.LayoutManager layoutManager = new GridLayoutManager(this, 2);
        teamsView.setLayoutManager(layoutManager);
    }
}
