package id.ac.polinema.infohewan;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;

import java.util.ArrayList;
import java.util.List;

import id.ac.polinema.infohewan.adapter.GridAdapter;
import id.ac.polinema.infohewan.model.GambarHewan;

public class Daftar2Activity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_daftar2);
        RecyclerView teamsView = findViewById(R.id.rv_teams);

        List<GambarHewan> teams = new ArrayList<>();
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/2/24/Oceanic_Whitetip_Shark.png", "Hiu", "Ikan Hiu adalah sekelompok (superordo Selachimorpha) ikan dengan kerangka tulang rawan yang lengkap [1] dan tubuh yang ramping. Mereka bernapas dengan menggunakan lima liang insang (kadang-kadang enam atau tujuh, tergantung pada spesiesnya) di samping, atau dimulai sedikit di belakang, kepalanya. Hiu mempunyai tubuh yang dilapisi kulit dermal denticles untuk melindungi kulit mereka dari kerusakan, dari parasit, dan untuk menambah dinamika air.[1] Mereka mempunyai beberapa deret gigi yang dapat digantikan.\n" +
                "\n" +
                "Hiu mencakup spesies yang berukuran sebesar telapak tangan. Hiu pigmi, Euprotomicrus bispinatus, sebuah spesies dari laut dalam yang panjangnya hanya 22 cm, hingga hiu paus, Rhincodon typus, ikan terbesar yang mampu tumbuh hingga sekitar 12 meter dan yang, seperti paus, hanya memakan plankton melalui alat penyaring di mulutnya. Hiu banteng, Carcharhinus leucas, adalah yang paling terkenal dari beberapa spesies yang berenang di air laut maupun air tawar (jenis ini ditemukan di Danau Nikaragua, di Amerika Tengah) dan di delta-delta.[2]"));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/4/49/Polbo_pulpo_galicia.jpg", "Gurita", "Gurita adalah hewan moluska dari kelas Cephalopoda (kaki hewan terletak di kepala), ordo Octopoda dengan terumbu karang di samudra sebagai habitat utama. Gurita terdiri dari 289 spesies yang mencakup sepertiga dari total spesies kelas Cephalopoda. Gurita dalam bahasa Inggris disebut Octopus (Yunani: Ὀκτάπους, delapan kaki) yang sering hanya mengacu pada hewan dari genus Octopus." +
                "\n" + "Gurita memiliki 8 lengan (bukan tentakel) dengan alat penghisap berupa bulatan-bulatan cekung pada lengan yang digunakan untuk bergerak di dasar laut dan menangkap mangsa. Lengan gurita merupakan struktur hidrostat muskuler yang hampir seluruhnya terdiri dari lapisan otot tanpa tulang atau tulang rangka luar. Tidak seperti hewan Cephalopoda lainnya, sebagian besar gurita dari subordo Incirrata mempunyai tubuh yang terdiri dari otot dan tanpa tulang rangka dalam. Gurita tidak memiliki cangkang sebagai pelindung di bagian luar seperti halnya Nautilus dan tidak memiliki cangkang dalam atau tulang seperti sotong dan cumi-cumi. Paruh adalah bagian terkeras dari tubuh gurita yang digunakan sebagai rahang untuk membunuh mangsa dan menggigitnya menjadi bagian-bagian kecil.\n" +
                "\n" +
                "Tubuh yang sangat fleksibel memungkinkan gurita untuk menyelipkan diri pada celah batuan yang sangat sempit di dasar laut, terutama sewaktu melarikan diri dari ikan pemangsa seperti belut laut Moray. Gurita yang kurang dikenal orang dari subordo Cirrata memiliki dua buah sirip dan cangkang dalam sehingga kemampuan untuk menyelip ke dalam ruangan sempit menjadi berkurang.\n" +
                "\n" +
                "Gurita mempunyai masa hidup yang relatif singkat dan beberapa spesies hanya hidup selama 6 bulan. Spesies yang lebih besar seperti Gurita raksasa Pasifik Utara yang beratnya bisa mencapai 40 kilogram bisa hidup sampai 5 tahun di bawah kondisi lingkungan yang sesuai. Reproduksi merupakan salah satu sebab kematian, gurita jantan hanya bisa hidup beberapa bulan setelah kawin dan gurita betina mati mati tidak lama setelah bertelur. Kematian disebabkan kelalaian gurita untuk makan selama sekitar satu bulan sewaktu menjaga telur-telur yang belum menetas.\n" +
                "\n" +
                "Selubung bagian perut tubuh gurita disebut mantel yang terbuat dari otot dan terlihat seperti kantung. Gurita memiliki tiga buah jantung yang terdiri dari dua buah jantung untuk memompa darah ke dua buah insang dan sebuah jantung untuk memompa darah ke seluruh bagian tubuh. Darah gurita mengandung protein Hemosianin yang kaya dengan tembaga untuk mengangkut oksigen. Dibandingkan dengan Hemoglobin yang kaya dengan zat besi, Hemosianin kurang efisien dalam mengangkut oksigen. Hemosianin larut dalam plasma dan tidak diikat oleh sel darah merah sehingga darah gurita berwarna biru pucat. Gurita bernapas dengan menyedot air ke dalam rongga mantel melalui kedua buah insang dan disemburkan keluar melalui tabung siphon. Gurita memiliki insang dengan pembagian yang sangat halus, berasal dari pertumbuhan tubuh bagian luar atau bagian dalam yang mengalami vaskulerisasi."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/f/f1/Chrysaora_Colorata.jpg", "Ubur-ubur", "Ubur-ubur adalah sejenis binatang laut tak bertulang belakang yang termasuk dalam filum Cnidaria, ubur-ubur yang dimaksud disini adalah hewan dari kelas Schypozoa, sehingga sering disebut ubur-ubur sejati agar tidak dibingungkan dengan hewan lain yang juga disebut ubur-ubur seperti: Ctenophora (ubur-ubur sisir) dan Cubozoa (ubur-ubur kotak). Sebagai anggota Cnidaria, mereka memiliki dua bentuk tubuh yaitu polip yang menempel di dasar laut dan medusa yang dapat berenang bebas dan berbentuk cangkir terbalik." +
                "\n" + "Umumnya mereka berukuran 2 sampai 40 cm, tapi ubur-ubur yang lebih besar bisa mencapai 1-2 meter, misalnya spesies terbesarnya Cyanea capillata atau lebih dikenal dengan Surai singa. Schypozoa dapat ditemukan di lautan di seluruh dunia, dari permukaan sampai laut dalam. Schypozoa tidak ditemukan di air tawar. Schypozoa memakan beragam makanan seperti Krustasea atau Ikan yang mereka buru menggunakan organel nematosista yang terdapat di tentakelnya. Nematosista sendiri adalah ciri khas filum Cnidaria, berupa sel berbentuk jarum yang berfungsi menusuk dan mengirim racun ke mangsanya." +
                "\n" + "Ubur-ubur dewasa memiliki dua bentuk tubuh dasar: Medusa yang dapat berenang bebas (motil) dan Polip yang menempel pada substrat (sesil). Kedua bentuk tersebut memiliki simetri radial. Hewan ini tidak punya kepala dan mulut serta anusnya terletak di lubang yang sama, sisi yang dekat mulut disebut oral dan sebaliknya disebut aboral. Ubur-ubur memiliki tentakel yang dipenuhi nematosista disisinya. Medusa memiliki mesoglea yang tebal dan elastis, sehingga medusa dapat meluncur di air dan bentuknya kembali seperti semula.[1]"));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/f/f4/Florida_Box_Turtle_Digon3_re-edited.jpg", "Kura-kura", "Kura-kura adalah hewan bersisik berkaki empat yang termasuk golongan reptil. Bangsa hewan yang disebut (ordo) Testudinata (atau Chelonians) ini khas dan mudah dikenali dengan adanya ‘rumah’ atau batok (bony shell) yang keras dan kaku.\n" +
                "\n" +
                "Batok kura-kura ini terdiri dari dua bagian. Bagian atas yang menutupi punggung disebut karapas (carapace) dan bagian bawah (ventral, perut) disebut plastron. Kemudian setiap bagiannya ini terdiri dari dua lapis. Lapis luar umumnya berupa sisik-sisik besar dan keras, dan tersusun seperti genting; sementara lapis bagian dalam berupa lempeng-lempeng tulang yang tersusun rapat seperti tempurung. Perkecualian terdapat pada kelompok labi-labi (Trionychoidea) dan jenis penyu belimbing, yang lapis luarnya tiada bersisik dan digantikan lapisan kulit di bagian luar tempurung tulangnya.\n" +
                "\n" +
                "Dalam bahasa Indonesia, kita mengenal tiga kelompok hewan yang termasuk bangsa ini, ialah penyu (bahasa Inggris: sea turtles), labi-labi atau bulus (freshwater turtles), dan kura-kura (tortoises). Dalam bahasa Inggris, dibedakan lagi antara kura-kura darat (land tortoises) dan kura-kura air tawar (freshwater tortoises atau terrapins)." +
                "\n" + "Kura-kura hidup di berbagai tempat, mulai daerah gurun, padang rumput, hutan, rawa, sungai dan laut. Sebagian jenisnya hidup sepenuhnya akuatik, baik di air tawar maupun di lautan. Kura-kura ada yang bersifat pemakan tumbuhan (herbivora), pemakan daging (karnivora) atau campuran (omnivora).\n" +
                "\n" +
                "Kura-kura tidak memiliki gigi. Akan tetapi perkerasan tulang di moncong kura-kura sanggup memotong apa saja yang menjadi makanannya.\n" +
                "\n" +
                "Ukuran tubuh kura-kura bermacam-macam, ada yang kecil ada yang besar. Biasanya ditunjukkan dengan panjang karapasnya (CL, carapace length). Kura-kura terbesar adalah penyu belimbing, yang karapasnya dapat mencapai panjang 300 cm. Labi-labi terbesar adalah labi-labi moncong babi, dengan panjang karapas sekitar 0.7 meter. Sementara kura-kura raksasa dari Kep. Galapagos dan Kep. Seychelles panjangnya dapat melebihi 0.7 meter. Sedangkan yang terkecil adalah kura-kura mini dari Afrika Selatan, yang panjang karapasnya tidak melebihi 8 cm.\n" +
                "\n" +
                "Kura-kura berbiak dengan bertelur (ovipar). Sejumlah beberapa butir (pada kura-kura darat) hingga lebih dari seratus butir telur (pada beberapa jenis penyu) diletakkan setiap kali bertelur, biasanya pada lubang pasir di tepi sungai atau laut, untuk kemudian ditimbun dan dibiarkan menetas dengan bantuan panas matahari. Telur penyu menetas kurang lebih setelah dua bulan (50-70 hari) tersimpan di pasir.\n" +
                "\n" +
                "Jenis kelamin anak kura-kura yang bakal lahir salah satunya ditentukan oleh suhu pasir tempat telur-telur itu tersimpan. Pada kebanyakan jenis kura-kura, suhu di atas rata-rata kebiasaan akan menghasilkan hewan betina. Dan sebaliknya, suhu di bawah rata-rata cenderung menghasilkan banyak hewan jantan.\n" +
                "\n" +
                "Kura-kura termasuk salah satu jenis hewan yang berumur panjang. Reptil ini dapat hidup puluhan tahun, bahkan seekor kura-kura darat dari Kep. Seychelles tercatat hidup selama 152 tahun (1766 – 1918)."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/3/3e/Blue_crab_on_market_in_Piraeus_-_Callinectes_sapidus_Rathbun_20020819-317.jpg", "Kepiting", "Kepiting adalah binatang anggota krustasea berkaki sepuluh dari upabangsa (infraordo) Brachyura, yang dikenal mempunyai \"ekor\" yang sangat pendek (bahasa Yunani: brachy = pendek, ura = ekor), atau yang perutnya (abdomen) sama sekali tersembunyi di bawah dada (thorax). Tubuh kepiting dilindungi oleh cangkang yang sangat keras, tersusun dari kitin, dan dipersenjatai dengan sepasang capit. Ketam adalah nama lain bagi kepiting.\n" +
                "\n" +
                "Kepiting terdapat di semua samudra dunia. Ada pula kepiting air tawar dan darat, khususnya di wilayah-wilayah tropis. Rajungan adalah kepiting yang hidup di perairan laut dan jarang naik ke pantai, sedangkan yuyu adalah ketam penghuni perairan tawar (sungai dan danau).\n" +
                "\n" +
                "Kepiting beraneka ragam ukurannya, dari ketam kacang, yang lebarnya hanya beberapa milimeter, hingga kepiting laba-laba Jepang, dengan rentangan kaki hingga 4 m [1]." +
                "\n" + "Kepiting sejati mempunyai lima pasang kaki; sepasang kaki yang pertama dimodifikasi menjadi sepasang capit dan tidak digunakan untuk bergerak. Di hampir semua jenis kepiting, kecuali beberapa saja (misalnya, Raninoida), perutnya terlipat di bawah cephalothorax. Bagian mulut kepiting ditutupi oleh maxilliped yang rata, dan bagian depan dari carapace tidak membentuk sebuah rostrum yang panjang [2]. Insang kepiting terbentuk dari pelat-pelat yang pipih (\"phyllobranchiate\"), mirip dengan insang udang, namun dengan struktur yang berbeda [3]."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/4/4b/Riccio_Melone_a_Capo_Caccia_adventurediving.it.jpg", "Bulu Babi", "Landak laut atau disebut juga bulu babi (Echinoidea) merupakan hewan laut yang berbentuk bundar dan memiliki duri pada kulitnya yang dapat digerakkan. Binatang ini terbagi menjadi sekitar 950 spesies dan dapat ditemukan mulai dari daerah pasang surut sampai di kedalaman 5.000 meter.[1]" +
                "\n" + "Seperti echinodermata lainnya, bulu babi memiliki lima simetri sebagai orang dewasa, tetapi larva pluteus mereka memiliki simetri bilateral (cermin) , yang menunjukkan bahwa mereka termasuk dalam Bilateria , kelompok besar filum hewan yang termasuk chordata , arthropoda , annelida dan moluska . Mereka tersebar luas di semua lautan, semua iklim dari tropis ke kutub, dan mendiami habitat bentik laut (dasar laut) dari pantai berbatu hingga kedalaman zona hadal . Echinoid memiliki catatan fosil yang kaya sejak masa Ordovisium , sekitar 450 juta tahun yang lalu. Kerabat terdekat mereka di antara echinodermata adalah teripang (Holothuroidea); keduanya deuterostoma , clade yang mencakup chordata .\n" +
                "\n" +
                "Hewan-hewan telah dipelajari sejak abad ke-19 sebagai organisme model dalam biologi perkembangan , karena embrio mereka mudah diamati; ini berlanjut dengan penelitian genom mereka karena simetri berlipat lima yang tidak biasa dan hubungannya dengan chordata. Spesies seperti landak pensil batu tulis populer di akuarium, di mana mereka berguna untuk mengendalikan ganggang. Bulu babi telah digunakan sebagai jimat pelindung."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/0/0b/KreeftbijDenOsse.jpg", "Lobster", "Lobster bercapit membentuk sebuah keluarga (Nephropidae, kadang kala juga Homaridae) dari crustacean besar laut. Mereka penting sebagai hewan, bisnis, dan makanan." +
                "\n" + "Lobster bercapit jangan dibingungkan dengan lobster spiny, yang tidak memiliki capit (chelae) dan tidak berhubungan dekat. Hubungan terdekat dari lobster bercapit adalah lobster reef Enoplometopus dan tiga keluarga dari crayfish air tawar." +
                "\n" + "Lobster kebanyakan datang dari pesisir timur laut Amerika Utara dengan Canadian Maritimes dan negara bagian Amerika Serikat Maine sebagai produsen terbesar. Mereka ditangkap dengan menggunakan jebakan lobster. Alat tersebut diberi umpan dan diturunkan ke dasar laut. Alat ini membiarkan lobster masuk, namun tidak mungkin bagi lobster besar untuk keluar. Alat ini membuat lobster kecil dapat keluar sehingga bisa mecegah penangkapan lobster yang berlebihan." +
                "\n" + "Lobster baru populer di pertengahan abad ke 19, diperkenalkan oleh penduduk New York dan Boston.[2] Ketika itu, kapal khusus juga dibangun untuk menjaga agar lobster yang ditangkap tetap hidup selama transportasi[3] Ketika itu lobster merupakan makanan orang miskin di Maine, Massachusetts, dan penduduk pinggir pantai Kanada.[4] Lobster ketika itu juga disajikan kepada narapidana untuk mengganggu selera makan mereka.[5] Pemanfaatan lainnya dari lobster ketika itu adalah sebagai bahan pupuk dan umpan ikan, dan baru dikalengkan pada awal abad ke 20.[6]\n" +
                "\n" +
                "Lobster umumnya dimasak dengan dikukus atau direbus.[7] Kadar merkuri dari lobster Amerika sekitar 0.31 ppm.[8]"));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/8/84/Zalophus_japonicus.JPG", "Singa Laut", "Singa laut adalah spesies pada enam genera pinnipedia modern. Habitat mereka meliputi perairan subarktik hingga tropis baik pada belahan bumi utara maupun belahan bumi selatan dengan pengecualian di samudra Atlantik."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/1/13/Walrus2.jpg", "Walrus", "Walrus (Odobenus rosmarus) adalah mamalia laut yang tersebar di Samudra Arktik dan Laut sub-Arktik di Belahan Utara Bumi. Walrus adalah satu-satunya spesies dalam keluarga Odobenidae dan genus Odobenus. Spesies ini terbagi menjadi 3 subspesies yaitu Walrus Atlantik, Walrus Pasifik, O. rosmarus laptevi.\n" +
                "\n" +
                "Walrus mudah dikenali karena memiliki gading. Walrus Pasifik dewasa dapat mencapai berat 1700 kg dan hanya dilampaui oleh anjing laut gajah. Hewan ini termasuk hewan sosial dan biasanya mencapai usia lanjut.\n" +
                "\n" +
                "Walrus memiliki peran penting dalam budaya orang Polar, yang memburu Walrus untuk daging, lemak, kulit, gading, dan tulangnya. Pada abad ke-19 dan ke-20 Walrus dieksploitasi untuk blubber dan gadingnya. Oleh karena itu jumlahnya menurun pada masa itu, tetapi jumlahnya telah meningkat kembali pada masa ini."));
        teams.add(new GambarHewan("https://asset.kompas.com/crop/83x53:717x475/750x500/data/photo/2018/09/01/2898637468.jpg", "Lumba-lumba", "Lumba-lumba adalah mamalia laut yang sangat cerdas, selain itu sistem alamiah yang melengkapi tubuhnya sangat kompleks. Sehingga banyak teknologi yang terinspirasi dari lumba-lumba. Salah satu contoh adalah kulit lumba-lumba yang mampu memperkecil gesekan dengan air, sehingga lumba-lumba dapat berenang dengan sedikit hambatan air. Hal ini yang digunakan para perenang untuk merancang baju renang yang mirip kulit lumba-lumba.\n" +
                "\n" +
                "Lumba-lumba memiliki sebuah sistem yang digunakan untuk berkomunikasi dan menerima rangsang yang dinamakan sistem sonar, sistem ini dapat menghindari benda-benda yang ada di depan lumba-lumba, sehingga terhindar dari benturan. Teknologi ini kemudian diterapkan dalam pembuatan radar kapal selam. Lumba-lumba adalah binatang menyusui karena lumba lumba adalah mamalia. Mereka hidup di laut dan sungai di seluruh dunia. Lumba-lumba adalah kerabat paus dan pesut. Ada lebih dari 40 jenis lumba-lumba.\n" +
                "\n" +
                "Bayi lumba-lumba yang baru lahir akan dibawa ke permukaan oleh induknya agar bisa menghirup udara. Lumba-lumba perlu naik ke permukaan untuk bernapas supaya tetap hidup. Lumba-lumba bernapas melalui lubang udara yang terletak di atas kepalnya. Tubuhnya yang licin dan ramping sangat sesuai untuk berenang. Induk lumba-lumba menyusui anaknya dengan susu yang gurih dan menyediakan energi bagi anaknya supaya cepat besar. Setiap anak lumba-lumba selalu berada di dekat induknya, sehingga ibunya bisa melindungi dari bahaya. Lumba-lumba selalu menjaga hubungan dengan anaknya hingga tumbuh semakin besar. Induk lumba-lumba memanggil anak anaknya dengan siulan khusus yang bisa mereka kenali.\n" +
                "\n" +
                "Lumba-lumba hidup dan bekerja dalam kelompok atau disebut kawanan. Mereka sering bermain bersama. Seekor lumba-lumba tidak bisa tidur nyenyak di bawah air. Ia bisa tenggelam. Oleh karena itu, ia setengah tidur beberapa saat dalam sehari. Lumba-lumba makan cumi dan ikan seperti ikan mullet abu-abu. Kadang kadang Lumba-lumba menggiring kawanan ikan agar mudah ditangkap. Lumba-lumba mencari jalan dengan mengirimkan suara di dalam air. Jika suara itu mengenai suatu benda, suara itu akan dipantulkan kembali sebagai gema. Kadang kadang, suara gaduh di laut akibat pengeboran minyak dapat membingungkan lumba-lumba. Mereka akan mengalami kesulitan dalam mengirim dan menerima pesan. Karena lumba-lumba dapat berkomunikasi, maka lumba-lumba disebut sebagai hewan yang paling cerdas, melebihi simpanse.[1]\n" +
                "\n" +
                "Manusia senantiasa tertarik dengan kisah lumba-lumba. Bangsa Romawi telah membuat gambar mozaik lumba-lumba sekitar 2.000 tahun lalu. Sekarang, manusia senang berenang di laut bersama binatang yang pandai dan bersahabat seperti lumba-lumba. Lumba-lumba harus berhati hati terhadap ikan hiu yang mungkin menyerang mereka sewaktu waktu. Mereka melindungi diri dengan gigi giginya, kadang-kadang mereka menggunakan paruhnya sebagai pelantak. Manusia dapat menjala banyak sekali ikan bagi lumba-lumba untuk makanannya. Terkadang, lumba-lumba tertangkap oleh jaring nelayan. Mereka tidak dapat menghirup napas di permukaan, akibatnya mereka tenggelam. Ketika bahan kimia yang berbahaya dibuang ke laut, limbah itu bisa meracuni makanan yang dimakan lumba-lumba. Pembangunan waduk di sungai dan pengeringan danau hanya menyisakan sedikit tempat bagi binatang seperti lumba-lumba Brazil untuk hidup.\n" +
                "\n" +
                "Lumba-lumba tergolong sebagai mamalia yang cerdas. Lumba-lumba dapat menolong manusia, bila lumba-lumba sudah terlatih, bahkan lingkaran api pun dapat mereka terobos. Singa laut, spesies primata, paus dan anjing juga termasuk binatang yang cerdas. Lumba-lumba yang sudah terlatih dapat melakukan berbagai atraksi dan mereka juga dapat berhitung, tetapi Lumba-lumba liar belum dapat melakukan berbagai atraksi. Sekarang ini, lumba-lumba dan paus sudah langka, maka lumba-lumba dan paus harus dilindungi. Lumba-lumba dan paus telah mulai dilindungi di seluruh dunia."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/0/07/Jumping_Humpback_whale.jpg", "Paus", "Paus atau lodan (khusus yang bergigi dan bukan berukuran kecil) adalah kelompok mamalia yang hidup di lautan. Sebutan \"paus\" diberikan pada anggota bangsa Cetacea yang berukuran besar. Paus bukan tergolong dalam keluarga ikan. Paus mempunyai ciri-ciri sebagai berikut:\n" +
                "\n" +
                "bernapas menggunakan paru-paru\n" +
                "mempunyai rambut (sedikit, kebanyakan ada di paus dewasa)\n" +
                "berdarah panas\n" +
                "mempunyai kelenjar susu\n" +
                "mempunyai jantung dengan empat ruang\n" +
                "Paus purba berevolusi pada pertengahan tempo Eocene, kira-kira 50 juta tahun yang lalu. Salah satu paus terawal yang telah punah adalah Basilosaurus yang mempunyai kepala kecil bermoncong menonjol dan bergigi. Basilosaurus mempunyai panjang 25 meter.\n" +
                "\n" +
                "Fosil menunjukkan bahwa paus berasal dari hewan daratan berkuku, kemungkinan dari hewan seperti Mesonychid (hewan seperti serigala yang tinggal di pesisir pantai) yang berangsur-angsur kembali menghunii lautan sekitar 50 juta tahun yang lalu. Satu lagi kemungkinan hewan lain yang berubah menjadi paus, adalah Ambulocetus, mamalia seukuran anjing laut namun memiliki panjang 3 meter seberat 325 kilogram.\n" +
                "\n" +
                "Pada masa kini dikenal dua kelompok paus, yaitu paus bergigi (Odontoceti) dan paus tidak bergigi (Mysticeti). Paus Odontoceti yang bergigi merupakan pemangsa yang memakan ikan, sotong, dan mamalia laut, mempunyai satu lubang pernapasan. Paus bergigi berkerabat dekat dengan lumba-lumba dan pesut. Paus tidak bergigi berukuran lebih besar daripada paus bergigi dan mempunyai struktur yang dikenal sebagai balin yang berbentuk sikat. Struktur ini berguna untuk menyaring plankton, makanannya, di air. Paus berbalin mempunyai dua lubang pernapasan."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/f/f6/Clown_fish_in_the_Andaman_Coral_Reef.jpg", "Nemo", "Ikan giru atau lebih dikenal dengan sebutan ikan badut adalah ikan dari anak suku Amphiprioninae dalam suku Pomacentridae.[1] Ada dua puluh delapan spesies yang biasa dikenali, salah satunya adalah genus Premnas, sementara sisanya termasuk dalam genus Amphiprion.[2] Mereka tersebar di lautan Pasifik, Laut Merah, lautan India, dan karang besar Australia.[3]\n" +
                "\n" +
                "Di alam bebas mereka bersimbiosis dengan anemon laut.[3] Anemon akan melindungi Ikan badut dari pemangsa dan Ikan badut akan membersihkan Anemon dengan memakan sisa - sisa makanan Anemon.[3] Ikan badut berwarna kuning, jingga, kemerahan atau kehitaman. Spesies terbesar mencapai panjang 18 cm, sementara yang terkecil hanya 6 cm.[3]"));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/8/8f/Electric-eel.jpg", "Belut Listrik", "Sidat listrik atau belut listrik (Electrophorus electricus) adalah sejenis ikan air tawar yang dapat menghasilkan aliran listrik kuat (sampai 650 volt) untuk berburu dan membela diri. Walaupun disebut sidat atau belut, ia termasuk anggota ordo Gymnotiformes, yang tidak mencakup keduanya.\n" +
                "\n" +
                "Sidat listrik biasa ditemukan di Sungai Amazon dan Sungai Orinoko serta daerah-daerah di sekitarnya. Ia bisa tumbuh hingga panjang 2,5 m (8,2 kaki) dan berat 20 kg (44 pound), walaupun biasanya ukuran rata-ratanya adalah 1 m."));
        teams.add(new GambarHewan("https://www.whitepaperconcept.com/wp-content/uploads/2014/05/godzilla-2014-review-spoileriffic-b0d6f9d3-c003-4191-82c4-65e101be7ca5.jpeg", "Godzila", "monster reptil hijau raksasa yang sangat terkenal sepanjang sejarah. Tetapi dibalik kepopulerannya itu ternyata ada beberapa hal yang masih menjadi tanda tanya bagi kebanyakan orang hingga saat ini seperti : dari manakah Godzilla berasal ? mahluk apakah Godzilla itu sebenarnya ? Siapakah orang orang brilian dibalik terciptanya sosok Godzilla ?. Semoga tulisan dibawah ini akan menjawab dan memuaskan semua rasa ingin tahu tentang Godzilla hingga tuntas mulai dari proses terciptanya Godzilla hingga ia menjadi monster yang sangat terkenal seperti saat ini.\n" +
                "\n" +
                "Pada tahun 1954 sebuah perahu nelayan di perairan Jepang secara tidak sengaja memasuki daerah percobaan tenaga atom yang memancarkan radiasi yang sangat besar. Akibatnya beberapa dari awak kapal tersebut harus dilarikan kerumah sakit dan beberapa dari mereka meninggal dunia. Kejadian tersebut menyebabkan tercemarnya ikan ikan yang telah terjual dipasaran Jepang , dan tentu saja hal ini menyebabkan kepanikan yang luar biasa di kalangan masyarakat Jepang.\n" +
                "\n" +
                "Tomoyuki Tanaka seorang produser film di Jepang lalu mendapat ide untuk menjadikan insiden itu sebagai tema dari film yang akan dibuatnya , langkah pertamanya ialah mencari kru kru film yang dianggapnya tepat untuk bergabung bersama dalam pembuatan film layar lebar yang akan disutradarai oleh dirinya sendiri. Ternyata keberuntungan masih berpihak pada Tanaka , hanya dalam waktu yang relatif singkat ia sudah dapat menemukan kru kru yang sangat berbakat seperti halnya Shigeru Kayama , seorang penulis cerita fiksi ilmiah yang mendapat tugas untuk menulis jalan cerita dari film monster yang akan dibuat oleh Tanaka ini. Lalu Eiji Tsuburaya yang telah berpengalaman membuat film film monster terkenal seperti King Kong yang akan bertugas bersama rekannya Teizo Toshimitsu untuk mendesain kostum Godzilla yang akan digunakan dalam film ( belakangan Eiji Tsuburaya mendirikan studionya sendiri yaitu Studio Tsuburaya dan ia menciptakan tokoh Ultraman , sehingga ia dikenal sebagai “ The Father of Ultraman ” ). Haruo Nakajima sebagai aktor di dalam Kostum Godzilla dan Akira Ifukube yang bekerja sebagai komposer musik dan sound effect dalam film ini. Dan yang terkahir ialah Inishiro Honda yang memimpin dan mengarahkan jalannyapembuatan film."));
        teams.add(new GambarHewan("https://cdn1-production-assets-kly.akamaized.net/medias/1398067/big/060181600_1478522884-kraken.jpg", "Kraken", "kraken ( / k r ɑː k ən / ) [1] adalah legendaris Cephalopoda -seperti rakasa laut dari ukuran raksasa di cerita rakyat Skandinavia . Menurut kisah - kisah Norse , kraken tinggal di lepas pantai Norwegia dan Greenland dan meneror pelaut terdekat . Penulis selama bertahun-tahun telah mendalilkan bahwa legenda mungkin berasal dari penampakan cumi-cumi raksasayang dapat tumbuh hingga 13-15 meter (40-50 kaki) panjangnya. Ukuran tipis dan penampilan menakutkan yang dikaitkan dengan kraken telah membuatnya menjadi monster yang hidup di lautan umum dalam berbagai karya fiksi . Kraken telah menjadi fokus banyak pelaut takhayul yang melewati Atlantik Utara dan terutama pelaut dari negara-negara Nordik karena kedekatannya dengan asal Skandinavia . Selama berabad-abad kraken telah menjadi bagian penting dari takhayul dan mitos para pelaut yang sangat terkait dengan kemampuan para pelaut dalam menceritakan sebuah kisah besar ." +
                "\n" + "kraken diambil dari modern bahasa Skandinavia , [2] [3] yang berasal dari Old Norse kata kraki . [4] Dalam bahasa Norwegia dan Swedia, Kraken adalah bentuk krake yang pasti , kata yang menunjuk binatang yang tidak sehat atau sesuatu yang bengkok ( mirip dengan penjahat dan engkol Inggris ). [5] Dalam bahasa Jerman modern , Krake (jamak dan menolak singular: Kraken) berarti gurita , tetapi juga dapat merujuk pada kraken yang legendaris. Kraken juga merupakan kata Norwegia kuno untuk gurita [4] dan eufemisme tua dalam bahasa Swedia untuk paus , digunakan ketika kata aslinya menjadi tabu karena diyakini dapat memanggil makhluk itu. [3] [6]"));
        teams.add(new GambarHewan("https://cdna.artstation.com/p/assets/images/images/018/435/968/large/felipe-vitti-mermaidman-baixa.jpg?1559357740", "Mermaid Man", "Mermaid Man , [2] adalah pahlawan super semi-pensiunan yang tinggal di Bikini Bottom . Dia dan sahabat karibnya  Barnacle Boy  adalah bintang-bintang dari pertunjukan-dalam-pertunjukan yang disebut The Adventures of Mermaid Man dan Barnacle Boy , tetapi mereka juga pahlawan super nyata dalam alam semesta SpongeBob SquarePants.\n" +
                "\n" +
                "Keduanya sekarang sangat tua dan saat ini berada di Shady Shoals Rest Home . Namun, dua penggemar terbesar mereka, SpongeBob SquarePants dan Patrick Star , meyakinkan mereka untuk keluar dari masa pensiun.\n" +
                "\n" +
                "Bersama dengan Barnacle Boy dan Grandma SquarePants , Mermaid Man adalah salah satu dari tiga karakter pendukung yang telah pensiun dari serial ini. Dia dan Barnacle Boy pensiun setelah aktor suara Mermaid Man, Ernest Borgnine , meninggal pada 2012 . Dia dan Barnacle Boy sekarang muncul sebagai mainan atau gambar. Aktor pengisi suara Barnacle Boy, Tim Conway, meninggal pada tahun 2019 ."));
        teams.add(new GambarHewan("http://media.sbmania.net/pictures/135a/280.png", "Bernacle Boy", "Barnacle Boy , [2] adalah sahabat karib Mermaid Man . Dia adalah pahlawan super dan parodi Aqualad dan Robin . Dia dikatakan berumur 68 tahun. [3] Ia pertama kali muncul dalam \" Mermaid Man and Barnacle Boy .\"\n" +
                "\n" +
                "Aktor suara Barnacle Boy, Tim Conway , meninggal pada 2019 . Bersama dengan Mermaid Man dan Grandma SquarePants , ia adalah salah satu dari tiga karakter pendukung yang telah pensiun dari seri. Ia menjadi pensiun dari seri bersama Mermaid Man sejak kematian Ernest Borgnine pada 2012 . Dia dan Mermaid Man sekarang muncul di gambar atau sebagai mainan. [4]"));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/2/29/Epinephelus_malabaricus.jpg", "Kerapu", "Kerapu adalah ikan anggota sejumlah genus dalam anaksuku Epinephelinae, suku Serranidae dalam seri Perciformes."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/9/9c/Anadara_granosa.jpg", "Kerang", "Kerang adalah hewan air yang termasuk hewan bertubuh lunak (moluska).\n" +
                "\n" +
                "Moluska bermanfaat\n" +
                "Coque blanche (Cerastoderma edule).jpg\n" +
                "Hasil laut (\"seafood\")\n" +
                "Abalon\n" +
                "Remis\n" +
                "Kerang\n" +
                "Periwinkel\n" +
                "Kupang\n" +
                "Tiram\n" +
                "Simping\n" +
                "Cumi-cumi\n" +
                "Gurita\n" +
                "Sotong\n" +
                "Industri perikanan\n" +
                "Budi daya perairan\n" +
                "Kotak ini: lihatbicarasunting\n" +
                "Pengertian kerang bersifat umum dan tidak memiliki arti secara biologi namun penggunaannya luas dan dipakai dalam kegiatan ekonomi.\n" +
                "\n" +
                "Dalam pengertian paling luas, kerang berarti semua moluska dengan sepasang cangkang (lihat Bivalvia). Dengan pengertian ini, lebih tepat orang menyebutnya kerang-kerangan dan sepadan dengan arti clam yang dipakai di Amerika. Contoh pemakaian seperti ini dapat dilihat pada istilah \"kerajinan dari kerang\".\n" +
                "Kata kerang dapat pula berarti semua kerang-kerangan yang hidupnya menempel pada suatu objek. Ke dalamnya termasuk jenis-jenis yang dapat dimakan, seperti kerang darah dan kerang hijau (kupang awung), tetapi tidak termasuk jenis-jenis yang dapat dimakan tetapi menggeletak di pasir atau dasar perairan, seperti lokan dan remis.\n" +
                "Kerang juga dipakai untuk menyebut berbagai kerang-kerangan yang bercangkang tebal, berkapur, dengan pola radial pada cangkang yang tegas. Dalam pengertian ini, kerang hijau tidak termasuk di dalamnya dan lebih tepat disebut kupang. Pengertian yang paling mendekati dalam bahasa Inggris adalah cockle.\n" +
                "Dalam pengertian yang paling sempit, yang dimaksud sebagai kerang adalah kerang darah (Anadara granosa), sejenis kerang budidaya yang umum dijumpai di wilayah Indo-Pasifik dan banyak dijual di warung atau rumah makan yang menjual hasil laut."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/4/4b/Hippocampus.jpg", "Kuda Laut", "Kuda laut adalah jenis ikan yang hidup di laut dari genus Hippocampus dan famili Syngnathidae. Hewan dengan ukuran yang bervariasi antara 16 mm (untuk spesies Hippocampus denise) sampai 35 cm ini dapat ditemukan di perairan tropis dan menengah di seluruh dunia. Kuda laut merupakan satu-satunya spesies yang jantannya dapat hamil.\n" +
                "\n" +
                "Sirip dorsal pada kuda laut terletak pada bagian bawah sedangkan sirip pektoralnya terletak pada bagian kepala, di dekat insang. Beberapa spesies kuda laut berwarna transparan sebagian, sehingga tidak mudah terlihat.\n" +
                "\n" +
                "Populasi kuda laut terancam karena penangkapan yang berlebihan. Kuda laut dimanfaatkan pada herbologi tradisional Tiongkok dan sebanyak 20 juta kuda laut telah ditangkap setiap tahunnya untuk keperluan ini. Impor ekspor kuda laut diatur dalam CITES sejak 15 Mei 2004."));

        GridAdapter adapter = new GridAdapter(this, teams);
        teamsView.setAdapter(adapter);

        RecyclerView.LayoutManager layoutManager = new GridLayoutManager(this, 2);
        teamsView.setLayoutManager(layoutManager);
    }
}
