package id.ac.polinema.infohewan;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;

import java.util.ArrayList;
import java.util.List;

import id.ac.polinema.infohewan.adapter.GridAdapter;
import id.ac.polinema.infohewan.model.GambarHewan;

public class Daftar4Activity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_daftar4);
        RecyclerView teamsView = findViewById(R.id.rv_teams);

        List<GambarHewan> teams = new ArrayList<>();
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/b/b2/Eunectes_murinus2.jpg", "Anakonda", "Anakonda (Bahasa latin: Eunectes=\"perenang handal\") adalah golongan ular besar yang endemik di perairan tawar dan sungai-sungai di daerah tropis Amerika Selatan.[1]" +
                "\n" + "Jenis terbesar dari anakonda adalah anakonda hijau (Eunectes murinus), yang juga merupakan ular terbesar di dunia menurut diameter badan maksimum. Spesimen terbesar yang pernah ditemui memiliki proporsi diameter tubuh mencapai 0.85 meter. Anakonda sebenarnya adalah golongan ular boa, tetapi tidak seperti boa jenis lain, anakonda adalah ular yang hidup di air atau tidak jauh dari air (semi-akuatik). Meskipun dapat memanjat pohon, ular ini lebih banyak menghabiskan waktu di dalam air.[2]" +
                "\n" + "Anakonda menjadi salah satu hewan yang melegenda. Ular ini memiliki reputasi sebagai ular raksasa yang mengerikan dan disebut-sebut sebagai ular pemangsa manusia, walaupun belum ada bukti kuat hingga saat ini. Banyak juga literatur yang menyebutkan bahwa anakonda juga ada di perairan hutan pedalaman Kalimantan. Tentu saja hal ini diragukan dan disebut \"mengada-ada\". Karena reputasinya itu, banyak cerita-cerita kontemporer dan film yang dibuat, dimana di dalamnya menceritakan tentang ular ini sebagai binatang buas.[3][4]\n" +
                "\n" +
                "Mengacu pada hal di atas, istilah \"anakonda\" sendiri memiliki asal-usul yang tidak jelas. Kata ini mungkin berasal dari bahasa Indian Tupi, suku asli penghuni wilayah bagian tengah sungai Amazon, yaitu Anacauchoa atau Anacaona. Kata ini diketahui adalah sebutan untuk ular raksasa penghuni sungai Amazon dalam cerita rakyat suku tersebut. Sebutan lokal untuk anakonda di Brazilia adalah Sucuri, Sucuriju, atau Sucuriuba.[5][6]"));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/f/f4/Florida_Box_Turtle_Digon3_re-edited.jpg", "Kura-kura", "Kura-kura adalah hewan bersisik berkaki empat yang termasuk golongan reptil. Bangsa hewan yang disebut (ordo) Testudinata (atau Chelonians) ini khas dan mudah dikenali dengan adanya ‘rumah’ atau batok (bony shell) yang keras dan kaku.\n" +
                "\n" +
                "Batok kura-kura ini terdiri dari dua bagian. Bagian atas yang menutupi punggung disebut karapas (carapace) dan bagian bawah (ventral, perut) disebut plastron. Kemudian setiap bagiannya ini terdiri dari dua lapis. Lapis luar umumnya berupa sisik-sisik besar dan keras, dan tersusun seperti genting; sementara lapis bagian dalam berupa lempeng-lempeng tulang yang tersusun rapat seperti tempurung. Perkecualian terdapat pada kelompok labi-labi (Trionychoidea) dan jenis penyu belimbing, yang lapis luarnya tiada bersisik dan digantikan lapisan kulit di bagian luar tempurung tulangnya.\n" +
                "\n" +
                "Dalam bahasa Indonesia, kita mengenal tiga kelompok hewan yang termasuk bangsa ini, ialah penyu (bahasa Inggris: sea turtles), labi-labi atau bulus (freshwater turtles), dan kura-kura (tortoises). Dalam bahasa Inggris, dibedakan lagi antara kura-kura darat (land tortoises) dan kura-kura air tawar (freshwater tortoises atau terrapins)." +
                "\n" + "Kura-kura hidup di berbagai tempat, mulai daerah gurun, padang rumput, hutan, rawa, sungai dan laut. Sebagian jenisnya hidup sepenuhnya akuatik, baik di air tawar maupun di lautan. Kura-kura ada yang bersifat pemakan tumbuhan (herbivora), pemakan daging (karnivora) atau campuran (omnivora).\n" +
                "\n" +
                "Kura-kura tidak memiliki gigi. Akan tetapi perkerasan tulang di moncong kura-kura sanggup memotong apa saja yang menjadi makanannya.\n" +
                "\n" +
                "Ukuran tubuh kura-kura bermacam-macam, ada yang kecil ada yang besar. Biasanya ditunjukkan dengan panjang karapasnya (CL, carapace length). Kura-kura terbesar adalah penyu belimbing, yang karapasnya dapat mencapai panjang 300 cm. Labi-labi terbesar adalah labi-labi moncong babi, dengan panjang karapas sekitar 0.7 meter. Sementara kura-kura raksasa dari Kep. Galapagos dan Kep. Seychelles panjangnya dapat melebihi 0.7 meter. Sedangkan yang terkecil adalah kura-kura mini dari Afrika Selatan, yang panjang karapasnya tidak melebihi 8 cm.\n" +
                "\n" +
                "Kura-kura berbiak dengan bertelur (ovipar). Sejumlah beberapa butir (pada kura-kura darat) hingga lebih dari seratus butir telur (pada beberapa jenis penyu) diletakkan setiap kali bertelur, biasanya pada lubang pasir di tepi sungai atau laut, untuk kemudian ditimbun dan dibiarkan menetas dengan bantuan panas matahari. Telur penyu menetas kurang lebih setelah dua bulan (50-70 hari) tersimpan di pasir.\n" +
                "\n" +
                "Jenis kelamin anak kura-kura yang bakal lahir salah satunya ditentukan oleh suhu pasir tempat telur-telur itu tersimpan. Pada kebanyakan jenis kura-kura, suhu di atas rata-rata kebiasaan akan menghasilkan hewan betina. Dan sebaliknya, suhu di bawah rata-rata cenderung menghasilkan banyak hewan jantan.\n" +
                "\n" +
                "Kura-kura termasuk salah satu jenis hewan yang berumur panjang. Reptil ini dapat hidup puluhan tahun, bahkan seekor kura-kura darat dari Kep. Seychelles tercatat hidup selama 152 tahun (1766 – 1918)."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/1/18/Bartagame_fcm.jpg", "Kadal", "Kadal atau bengkarung adalah kelompok reptilia bersisik berkaki empat (beberapa spesies tidak berkaki dan mirip ular, tetapi bukan ular) yang tersebar sangat luas di dunia. Secara ilmiah, kelompok besar ini dikenal sebagai subordo atau anak bangsa Lacertilia (beberapa literatur menyebut Sauria) yang merupakan anggota dari bangsa reptilia bersisik (Squamata) bersama dengan ular.[1]\n" +
                "\n" +
                "Secara umum, istilah \"kadal\" atau \"bengkarung\" (bahasa Inggris: lizards) juga mencakup kelompok cecak, tokek, bunglon, cecak terbang, biawak, iguana, dan lain-lain. Sedangkan secara sempit, istilah kadal (dan bengkarung) dalam bahasa Indonesia hanya merujuk kepada kelompok kadal yang umumnya bertubuh kecil, padat, bersisik licin dan berkilau, serta hidup di tanah (Ingg.: skink, yaitu semua jenis dari famili Scincidae, atau jenis-jenis dari infraordo Scincomorpha). Kadal pada umumnya memiliki empat kaki, lubang telinga luar, dan kelopak mata yang dapat dibuka-ditutup. Walau begitu, ada pula jenis-jenis yang tidak memiliki sebagian ciri itu. Contohnya adalah ular kaca (glass snake atau glass lizard, suku Anguidae) yang tidak memiliki kaki fisik sehingga menyerupai ular, tetapi masih bisa dibedakan dengan ular berdasarkan ciri-ciri yang lain.[2]"));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/f/f1/Tyrannosaurus_rex_by_durbed.jpg", "Dinosaurus", "Dinosaurus adalah kelompok hewan purbakala dari klad Dinosauria. Dinosaurus pertama kali muncul pada periode Trias, sekitar 230 juta tahun yang lalu, dan merupakan vertebrata dominan selama 135 juta tahun, yang dimulai sejak periode Jura (sekitar 201 juta tahun yang lalu) hingga berakhirnya periode Kapur (65 juta tahun yang lalu), dan kemudian musnah akibat peristiwa kepunahan Kapur-Paleogen sebelum Era Mesozoikum. Studi terhadap fosil dinosaurus menunjukkan bahwa spesies burung berevolusi dari dinosaurus theropoda selama periode Jura, dan akibatnya, ribuan jenis burung yang hidup sekarang telah diklasifikasikan sebagai sub-kelompok dinosaurus oleh para paleontolog.[1] Beberapa burung yang selamat dari kepunahan 66 juta tahun yang lalu beserta keturunannya melanjutkan keberlangsungan hidup dinosaurus sampai sekarang.[2]\n" +
                "\n" +
                "Dinosaurus bisa digolongkan ke dalam beragam kelompok hewan dari sudut pandang taksonomi, morfologi, dan ekologi. Lebih dari 9.000 spesies burung adalah jenis dinosaurus vertebrata yang paling beragam, selain perciform ikan.[3] Dengan menggunakan bukti fosil, para paleontolog telah mengidentifikasi lebih dari 500 genera dinosaurus yang berbeda,[4] dan lebih dari 1.000 spesies yang tidak sama dengan dinosaurus nonburung.[5] Jenis dinosaurus di setiap benua bisa ditentukan melalui spesies yang masih hidup ataupun melalui sisa-sisa fosil.[6] Kebanyakan di antaranya adalah herbivora, sedangkan yang selebihnya adalah karnivora. Sebagian besar keturunan dinosaurus yang masih hidup adalah bipedal (berkaki dua), tetapi kebanyakan jenis dinosaurus yang telah punah adalah spesies quadrupedal (berkaki empat). Struktur tampilan yang rumit seperti tanduk atau jambul umumnya dimiliki oleh semua kelompok dinosaurus, dan beberapa kelompok yang telah punah juga memiliki struktur tulang yang khas seperti duri dan tulang punggung yang tajam. Penelitian menunjukkan bahwa bertelur dan membangun sarang adalah karakteristik lainnya yang dimiliki oleh semua dinosaurus. Meskipun spesies burung modern pada umumnya berukuran kecil karena menyesuaikan dengan kemampuan terbang, sebagian besar dinosaurus pra-sejarah berukuran besar—yang terbesar adalah Amphicoelias fragilimus dari sauropoda, dengan panjang 60 meter (200 kaki) dan tinggi 10 meter (30 kaki) dengan berat 150 ton.[7] Namun, anggapan bahwa dinosaurus nonburung pada umumnya berukuran raksasa adalah suatu kesalahpahaman; banyak juga dinosaurus yang berukuran kecil, misalnya Xixianykus, yang panjangnya hanya 50 cm (20 inci).\n" +
                "\n" +
                "Meskipun kata dinosaurus secara harfiah berarti \"kadal yang mengerikan\", tetapi sebenarnya dinosaurus bukanlah spesies kadal. Sebaliknya, dinosaurus tergolong dalam kelompok reptil yang terpisah. Bukti menunjukkan bahwa dinosaurus yang telah punah sama sekali tidak mencerminkan karakteristik tradisional reptil, misalnya bergerak melata dan ektoterma. Selain itu, kebanyakan hewan pra-sejarah seperti mosasaurus, ichthyosaurus, pterosaurus, plesiosaurus, dan Dimetrodon, dianggap sebagai jenis dinosaurus, tetapi sebenarnya hewan-hewan ini bukanlah dinosaurus. Sepanjang paruh pertama abad ke-20, sebelum burung diakui sebagai keturunan dinosaurus, sebagian besar ilmuwan percaya bahwa dinosaurus adalah hewan yang lamban dan berdarah dingin. Namun, penelitian yang dilakukan sejak 1970-an menunjukkan bahwa dinosaurus adalah hewan yang aktif dengan sistem metabolisme yang tinggi dan melakukan berbagai adaptasi dalam interaksi sosialnya.\n" +
                "\n" +
                "Sejak fosil dinosaurus ditemukan pertama kali pada awal abad ke-19, rangkaian kerangka dinosaurus telah menjadi atraksi utama di berbagai museum di seluruh dunia, dan dinosaurus juga telah menjadi bagian yang tak terpisahkan dari kebudayaan dunia. Ukurannya yang besar serta sifatnya yang dianggap buas dan mengerikan telah menyebabkan munculnya buku-buku dan film-film laris yang mengisahkan mengenai dinosaurus, misalnya Jurassic Park. Tingginya antusiasme publik terhadap dinosaurus menyebabkan meningkatnya aliran dana untuk membiayai penelitian dinosaurus, dan penemuan-penemuan terbaru secara teratur selalu diliput oleh media."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/7/71/G_gecko_070101_2323_kng.jpg", "Tokek", "Tokek adalah nama umum untuk menyebut cecak besar atau jenis-jenis kadal dari suku Gekkonidae. Namun istilah tokek secara sempit biasa merujuk pada jenis-jenis dari marga Gekko, suku Gekkonidae. Sedangkan tokek dalam pemahaman orang awam merujuk kepada tokek rumah (Gekko gecko), yang memiliki agihan yang luas dan sangat sering dijumpai karena hidup di lingkungan manusia.[1]\n" +
                "\n" +
                "Tokek menyebar luas di Asia Selatan dan Asia Tenggara, ke utara hingga Korea dan Jepang, lalu ke timur --meliputi Kepulauan Nusantara dan Filipina-- hingga Kepulauan Solomon dan Santa Cruz di Pasifik.[2]" +
                "\n" + "Tokek berkerabat dekat dengan cecak dan keduanya merupakan hewan yang dapat memutuskan dan menumbuhkan ekornya (autotomi), tetapi tokek berukuran lebih besar. Kulit punggung ditutupi oleh sisik-sisik samar (granular) dengan bintil-bintil yang agak besar dan menonjol. Pupil mata tegak bentuk jorong, dengan tepian yang bergerigi. Jari-jari kaki depan dan belakang tumbuh sempurna, melebar di ujung, terkadang dengan selaput di antara pangkal jari. Cakar (kuku) terdapat pada ujung jari bagian bawah. Sisi bawah jari dihiasi dengan bantalan pelekat (disebut scansor) yang berguna untuk menahan langkah agar tidak jatuh, biasanya digunakan ketika memanjat pohon, dinding atau langit-langit rumah.[1]\n" +
                "\n" +
                "Tokek biasanya aktif di saat senja dan malam hari. Ciri khas tokek adalah sering mengeluarkan suara panggilan ketika menjelang malam, meski suara panggilannya kadang-kadang terdengar di siang hari. Tokek tinggal di lubang pepohonan di hutan atau di bawah kayu atau bebatuan, tetapi sering juga berada di lingkungan manusia, biasanya di balik lemari atau di gudang. Tokek adalah pemakan serangga yang masif, namn mereka juga memburu makanan lain, seperti cacing, dan terkadang reptilia yang lebih kecil. Tokek betina berkembangbiak dengan bertelur, biasanya diletakkan menempel di sudut lubang atau dinding, sering pula di balik lemari atau pajangan di dalam rumah. Tempat menyimpan telur ini biasanya akan digunakan berulang kali oleh tokek yang sama.[1]"));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/1/1f/Kadal_Kebun_%28Mabouya_multifasciata%29.jpg", "Kadal Kebun", "Kadal kebun atau juga disebut bengkarung biasa, bengkarung kebun, atau oleh orang awam cukup disebut kadal, adajah salah satu jenis kadal yang paling sering dijumpai di Indonesia. Kadal ini termasuk kedalam suku Scincidae (bengkarungan). Nama umumnya dalam bahasa Inggris adalah East Indian Brown Skink, Many-lined Sun Skink, atau Common Sun Skink, sedangkan nama ilmiahnya, Eutropis multifasciata, merujuk pada pola garis-garis samar memanjang di sisi tubuhnya. Sebelumnya, kadal ini (dan juga semua jenis Eutropis Sp.) digolongkan ke dalam genus Mabuya Sp.. Sekarang, genus Mabuya hanya merujuk pada jenis-jenis yang terdapat di benua Amerika." +
                "\n" + "Kadal ini berukuran agak kecil, spesimen yang sering ditemui sehari-hari berukuran sebesar jempol kaki dengan panjang antara 18 hingga 22 cm dengan sekitar 60% dari panjangnya adalah panjang ekor. Kepalanya berbentuk lancip dengan leher yang sangat pendek. Penampang badannya berbentuk persegi atau kotak. Tubuh bagian atas berwarna coklat tua atau cokelat keabu-abuan mengkilap dengan sisi tubuh berwarna keemasan, terutama dekat leher. Terkadang juga dihiasi bintik-bintik kecil berwarna hitam dan/atau pucat di punggung dan sisi badannya. Bagian leher bawah berwarna cokelat muda dan bagian perut hingga anus berwarna cokelat pucat. Moncong/bibir mulut berwarna kemerah-merahan. Ekor berwarna sama dengan tubuhnya, dengan dihiasi garis samar berwarna gelap di sisi ekor. Lengan kaki juga berwarna sama dengan tubuh atasnya.[1]."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/8/84/Schoenechse.jpg", "Bunglon", "Bunglon[1] (Calotes) adalah sebutan khusus untuk beraneka jenis kadal/bengkarung yang memiliki kemampuan mengubah warna kulitnya.[2] Secara umum, istilah \"bunglon\" digunakan untuk menyebut kadal-kadal dari suku Iguania termasuk Iguanidae, agamidae dan chamaeleonidae.[3]\n" +
                "\n" +
                "Istilah dalam bahasa Inggris adalah Chameleon atau Chamaeleon.[4][5][6] Akan tetapi, istilah dalam bahasa Inggris tersebut lebih sering digunakan untuk menyebut jenis-jenis dari suku Chamaeleonidae. Untuk istilah bunglon dalam bahasa Indonesia lebih cocok diterjemahkan dengan istilah calotes, karena kadal jenis chameleonidae tidak ditemukan di kawasan Indonesia.[7]\n" +
                "\n" +
                "Bunglon menyebar sangat luas mulai dari sebagian Asia bagian selatan, hingga kepulauan Nusantara. Di Indonesia sendiri, istilah bunglon digunakan untuk menyebut beberapa spesies dari marga Bronchocela Sp., misalnya bunglon surai.[8]"));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/8/85/Iguana_iguana.jpg", "Iguana", "Iguana adalah marga kadal yang hidup di daerah tropis Amerika Tengah, Amerika Selatan, dan kepulauan Karibia. Kadal-kadal ini dideskripsikan pertama kali oleh seorang ahli hewan berkebangsaan Austria, Josephus Nicolaus Laurenti pada tahun 1768. Sejauh ini, genus Iguana hanya terdiri dari dua spesies, yaitu iguana hijau (Iguana iguana) dan iguana Antilles Kecil (Iguana delicatissima)." +
                "\n" + "Istilah \"iguana\" diketahui kemungkinan berasal dari bahasa Taino (salah satu suku asli Amerika) yaitu \"iwana\" yang juga merujuk pada kadal-kadal ini.[1]\n" +
                "\n" +
                "Panjang tubuh iguana antara 1.5 meter hingga 1.8 meter, termasuk panjang ekor. Ciri khas dari iguana adalah memiliki jambul (seperti pada ayam jantan) di bawah rahang mereka, serta deretan sisik membentuk duri besar di tubuh bagian atasnya, yang berjejer dari leher hingga pangkal ekor. Selain itu, iguana juga memiliki organ tubuh mirip mata pada bagian atas kepalanya. Organ tersebut berfungsi untuk menganalisis cahaya di sekitarnya. Warna tubuh iguana bervariasi, mulai dari hijau terang, hijau kecokelatan, hijau lumut, hijau kekuningan atau keabu-abuan, atau cokelat karamel. Ekor iguana berwarna sama dengan tubuh dan dihiasi dengan belang belang hitam atau gelap dari pangkal hingga ujung.[2][3]\n" +
                "\n" +
                "Iguana telah beradaptasi dengan baik sebagai kadal pohon dan kadal pemakan tumbuhan (herbivora). Akan tetapi, mereka tetap memerlukan nutrisi hewani, biasanya dengan memakan serangga kecil yang ada di tumbuhan yang mereka makan."));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/8/81/Komodo_dragon_Varanus_komodoensis_Ragunan_Zoo_2.JPG", "Komodo", "Komodo, atau juga disebut biawak komodo (Varanus komodoensis), adalah spesies biawak besar yang terdapat di Pulau Komodo, Rinca, Flores, Gili Motang, dan Gili Dasami di Provinsi Nusa Tenggara Timur, Indonesia.[1][2] Biawak ini oleh penduduk asli pulau Komodo juga disebut dengan nama setempat ora.[3]\n" +
                "\n" +
                "Komodo merupakan spesies terbesar dari familia Varanidae, sekaligus kadal terbesar di dunia, dengan rata-rata panjang 2-3 meter dan beratnya bisa mencapai 100 kg. Komodo merupakan pemangsa puncak di habitatnya karena sejauh ini tidak diketahui adanya hewan karnivora besar lain selain biawak ini di sebarang geografisnya.[4][5][6]\n" +
                "\n" +
                "Tubuhnya yang besar dan reputasinya yang mengerikan membuat mereka menjadi salah satu hewan paling terkenal di dunia. Sekarang, habitat komodo yang sesungguhnya telah menyusut akibat aktivitas manusia, sehingga lembaga IUCN memasukkan komodo sebagai spesies yang rentan terhadap kepunahan. Biawak komodo telah ditetapkan sebagai hewan yang dilindungi oleh pemerintah Indonesia dan habitanya dijadikan taman nasional, yaitu Taman Nasional Komodo, yang tujuannya didirikan untuk melindungi mereka." +
                "\n" + "Komodo liar dewasa biasanya memiliki berat sekitar 70 kg,[7] tetapi komodo yang dipelihara di penangkaran sering kali memiliki bobot yang lebih berat. Spesimen liar terbesar yang pernah ditemukan panjangnya mencapai 3.13 meter dengan berat sekitar 166 kg, termasuk berat makanan yang belum dicerna di dalam perutnya.[8] Komodo memiliki ekor yang sama panjang dengan tubuhnya. Meskipun komodo tercatat sebagai kadal terbesar di dunia, namun bukan spesies yang terpanjang. Reputasi panjang tubuh (tidak termasuk berat badan) dipegang oleh biawak Papua (Varanus salvadorii).[9] Komodo jantan lebih besar daripada komodo betina, dengan warna kulit dari abu-abu gelap sampai merah batu bata, sementara komodo betina biasanya berwarna hijau kecokelatan dan memiliki bercak kecil kuning pada tenggorokannya. Komodo muda lebih bervariasi warnanya, dengan warna kuning, hijau dan putih dengan latar belakang hitam.[10]\n" +
                "\n" +
                "Di dalam mulut komodo dewasa, terdapat sekitar 60 buah gigi yang bergerigi tajam sepanjang sekitar 2.5 cm, yang sering terlepas atau ditanggalkan.[10][11] Komodo memiliki lidah yang panjang, berwarna kuning kecokelatan dan bercabang.[8] Air liur komodo merupakan salah satu hal yang sering dibicarakan banyak orang karena kebanyakan orang menganggapnya beracun seperti bisa ular atau kadal beracun, bahkan dianggap tidak ada obatnya, baik untuk mencegah maupun menetralkan racun tersebut. Walau begitu, hal ini menjadi perdepatan panjang diantara para ahli hewan di dunia.[12]" +
                "\n" + "Komodo mampu melihat hingga sejauh 300 m, namun karena retinanya hanya memiliki sel kerucut, hewan ini tidak dapat melihat dengan baik di kegelapan malam. Komodo mampu membedakan warna namun tidak begitu mampu membedakan objek yang tak bergerak.[13] Komodo tidak memiliki indera pendengaran, walaupun memiliki lubang telinga.[14]\n" +
                "\n" +
                "Komodo menggunakan lidahnya untuk mencium bau mangsanya seperti halnya sebagian besar Squamata. Lidah komodo menangkap partikel bau di udara lalu menaruhnya ke organ di langit-langit mulutnya yang disebut organ Jacobson yang berfungsi untuk menganalisis tanda-tanda dari bau tersebut.[15] Dengan bantuan angin dan kebiasaannya menolehkan kepalanya ke kanan dan ke kiri ketika berjalan, komodo dapat mendeteksi keberadaan daging bangkai sejauh 4—9.5 km.[10] Lubang hidung komodo hanya berfungsi untuk bernafas dan bukan mencium bau karena komodo tidak memiliki selaput penerima bau di hidungnya.[16] Komodo juga tidak memiliki organ perasa di lidahnya, hanya ada sedikit ujung-ujung saraf perasa di tenggorokan dalam.[15]\n" +
                "\n" +
                "Komodo sempat dianggap tuli ketika penelitian mendapatkan bahwa bisikan, suara yang meningkat dan teriakan ternyata tidak memengaruhi komodo tersebut. Hal ini kemudian terbantahkan ketika karyawan Kebun Binatang London ZSL, Joan Proctor melatih biawak komodo untuk keluar makan dengan suaranya, bahkan juga ketika ia tidak terlihat oleh si biawak.[17]"));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/8/88/Monitor_lizard_in_Kalahari.JPG", "Biawak", "Biawak adalah sebangsa kadal berukuran menengah dan besar yang tersebar di daerah beriklim panas dan tropis Afrika, Asia, dan Australia. Nama umumnya dalam bahasa Melayu, juga bahasa Indonesia adalah \"Biawak\". Nama-nama umum lain di antaranya \"bayawak\" (Sunda); \"bajul\", \"menyawak\" atau \"nyambik\" (Jawa, istilah \"bajul\" juga merujuk pada buaya); \"berekai\" (Madura); dan \"hora\" atau \"mbu\" (sebutan untuk biawak Komodo oleh penduduk pulau Komodo dan pulau Rinca). Dalam bahasa Inggris disebut monitor lizard, goanna, atau \"dragon\" (istilah \"dragon\" atau \"naga\" juga merujuk pada ular).[1][2]\n" +
                "\n" +
                "Jenis biawak terbesar dan terkenal di dunia ialah komodo (Varanus komodoensis), yang panjangnya dapat melebihi 3 m. Biawak ini memburu hewan-hewan berukuran menengah dan besar seperti rusa, babi hutan dan anak kerbau. Bahkan ada kasus-kasus Komodo menyerang manusia, meskipun jarang. Biawak ini hanya menyebar terbatas di beberapa pulau kecil di Nusa Tenggara, seperti di Pulau Komodo, Pulau Rinca, Pulau Padar, dan di pantai barat Pulau Flores.[3] Biawak yang kerap ditemui di desa-desa dan perkotaan di Indonesia adalah biawak air dari jenis Varanus salvator. Panjang tubuhnya (moncong hingga ujung ekor) umumnya hanya sekitar 1 meter, meskipun ada pula yang dapat mencapai 2,5 meter.[4]" +
                "\n" + "Biawak biasanya tinggal tidak jauh dari perairan, biasanya di hutan lembab, padang rumput, dan sekitar hilir sungai. Di daerah perkotaan, biawak kerap ditemukan di gorong-gorong saluran air yang bermuara ke sungai. Biawak memakan meragam jenis makanan, mulai dari serangga, ketam, berbagai jenis kodok, ikan, reptilia kecil, burung, serta mamalia kecil seperti tikus dan cerurut. Jenis-jenis besar seperti Komodo juga memangsa hewan besar seperti rusa atau babi hutan.Biawak juga kerap mencuri dan memakan telur atau memangsa anak burung. Sering ditemui biawak mengambil dan memakan telur kura-kura, penyu atau telur buaya.[5][6][7]"));
        teams.add(new GambarHewan("https://upload.wikimedia.org/wikipedia/commons/7/74/Crocodile_Crocodylus-porosus_amk.jpg", "Buaya", "Buaya adalah reptil bertubuh besar yang hidup di air. Secara ilmiah, buaya meliputi seluruh spesies anggota suku Crocodylidae, termasuk pula buaya sepit (Tomistoma schlegelii). Meski demikian nama ini dapat pula dikenakan secara longgar untuk menyebut ‘buaya’ aligator, kaiman dan gavial; yakni kerabat-kerabat buaya yang berlainan suku.\n" +
                "\n" +
                "Buaya umumnya menghuni habitat perairan tawar seperti sungai, danau, rawa dan lahan basah lainnya, namun ada pula yang hidup di air payau seperti buaya muara. Makanan utama buaya adalah hewan-hewan bertulang belakang seperti bangsa ikan, reptil dan mamalia, kadang-kadang juga memangsa moluska dan krustasea bergantung pada spesiesnya. Buaya merupakan hewan purba, yang hanya sedikit berubah karena evolusi semenjak zaman dinosaurus.\n" +
                "\n" +
                "Dikenal pula beberapa nama daerah untuk menyebut buaya, seperti misalnya buhaya (Sd.); buhaya (bjn); baya atau bajul (Jw.); bicokok (Btw.), bekatak, atau buaya katak untuk menyebut buaya bertubuh kecil gemuk; senyulong, buaya jolong-jolong (Mly.), atau buaya julung-julung untuk menyebut buaya ikan; buaya pandan, yakni buaya yang berwarna kehijauan; buaya tembaga, buaya yang berwarna kuning kecoklatan; dan lain-lain.\n" +
                "\n" +
                "Dalam bahasa Inggris buaya dikenal sebagai crocodile. Nama ini berasal dari penyebutan orang Yunani terhadap buaya yang mereka saksikan di Sungai Nil, krokodilos; kata bentukan yang berakar dari kata kroko, yang berarti ‘batu kerikil’, dan deilos yang berarti ‘cacing’ atau ‘orang’. Mereka menyebutnya ‘cacing bebatuan’ karena mengamati kebiasaan buaya berjemur di tepian sungai yang berbatu-batu."));
//        teams.add(new GambarHewan("", "", ""));
//        teams.add(new GambarHewan("", "", ""));
//        teams.add(new GambarHewan("", "", ""));
//        teams.add(new GambarHewan("", "", ""));
//        teams.add(new GambarHewan("", "", ""));
//        teams.add(new GambarHewan("", "", ""));
//        teams.add(new GambarHewan("", "", ""));
//        teams.add(new GambarHewan("", "", ""));
//        teams.add(new GambarHewan("", "", ""));

        GridAdapter adapter = new GridAdapter(this, teams);
        teamsView.setAdapter(adapter);

        RecyclerView.LayoutManager layoutManager = new GridLayoutManager(this, 2);
        teamsView.setLayoutManager(layoutManager);
    }
}
